In [1]:
import pandas as pd
import pandas as pd
from utils import snowflake_login, descargar_segmento, get_credentials
from datetime import datetime

In [27]:
cab_base = pd.read_csv('Cabeceras Marcos_2026-03-19-1153.csv')
cab_base

,FECHA_INICIO,FECHA_FIN,GEOG_LOCL_ID,GEOG_LOCL_COD,GEOG_LOCL_DESC,SECCION,PUNTERA,DURACION_PUNTERA,GRUPO,DEPT,...,ITEM,ARTC_ARTC_DESC,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,VENTA_BASAL,ACELERACION,VENTA_ACELERADA_DIARIA,CARGA_SUGERIDA_X_VENTA,DOH_CARGA_MAX,DOH_CARGA_MIN
0,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055017,GALLETAS PASEO 5 SEMILLAS 300 GR,30,20,1.41,1.04,1.47,44.1,20.41,13.61
1,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055007,GALLETA PASEO SALVADO 300 GR,20,20,0.64,1.00,0.64,19.2,31.25,31.25
2,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055015,GALLETA PASEO MULTICEREAL 300 GR,30,20,0.91,1.00,0.91,27.3,32.97,21.98
3,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000369385,GALLETA PASEO SESAMO 300 GR,36,18,0.52,1.00,0.52,15.6,69.23,34.62
4,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055014,GALLETA PASEO SIN SAL 300 GR,30,20,0.29,1.15,0.33,9.9,90.91,60.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4577,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000568936,FRUTTE SIN AZUCAR MANGO NARANJA 600 ML,72,36,0.88,1.09,0.96,28.8,75.00,37.50
4578,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000049601,SALUS FRUTTE MANZANA 600 ML,72,36,0.52,1.06,0.55,16.5,130.91,65.45
4579,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000049604,SALUS FRUTTE NARANJA CERO 600 ML,72,36,0.40,1.32,0.53,15.9,135.85,67.92
4580,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000568931,SALUS FRUTTE MANZANA UVA 600 ML,72,36,0.50,1.00,0.50,15.0,144.00,72.00
4581,2026-04-01,2026-04-30,62,411,Express Rivera,Almacen,CABECERA MONDELEZ 1,30,COMESTIBLES,GALLETAS,...,1000055125,GALLETA RELLENA OREO REGULAR 354 GR,35,10,1.07,1.00,1.07,32.1,32.71,9.35

In [28]:
cab_view = pd.read_csv('Cabeceras Marcos_view.csv')
cab_view

,FECHA_INICIO,FECHA_FIN,GEOG_LOCL_ID,GEOG_LOCL_COD,GEOG_LOCL_DESC,SECCION,PUNTERA,DURACION_PUNTERA,GRUPO,DEPT,...,ITEM,ARTC_ARTC_DESC,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,VENTA_BASAL,ACELERACION,VENTA_ACELERADA_DIARIA,CARGA_SUGERIDA_X_VENTA,DOH_CARGA_MAX,DOH_CARGA_MIN
0,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055017,GALLETAS PASEO 5 SEMILLAS 300 GR,30,20,1.41,1.04,1.47,44.1,20.41,13.61
1,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055007,GALLETA PASEO SALVADO 300 GR,20,20,0.64,1.00,0.64,19.2,31.25,31.25
2,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055015,GALLETA PASEO MULTICEREAL 300 GR,30,20,0.91,1.00,0.91,27.3,32.97,21.98
3,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000369385,GALLETA PASEO SESAMO 300 GR,36,18,0.52,1.00,0.52,15.6,69.23,34.62
4,2026-04-01,2026-04-30,21,101,Hiper Cordon,Almacen,CABECERA CAÑUELAS,30,COMESTIBLES,GALLETAS,...,1000055014,GALLETA PASEO SIN SAL 300 GR,30,20,0.29,1.15,0.33,9.9,90.91,60.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4582,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000568936,FRUTTE SIN AZUCAR MANGO NARANJA 600 ML,72,36,0.88,1.09,0.96,28.8,75.00,37.50
4583,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000049601,SALUS FRUTTE MANZANA 600 ML,72,36,0.52,1.06,0.55,16.5,130.91,65.45
4584,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000049604,SALUS FRUTTE NARANJA CERO 600 ML,72,36,0.40,1.32,0.53,15.9,135.85,67.92
4585,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Bebidas,CABECERA SALUS II,30,BEBIDAS,BEB. NO ALCOHOLICAS,...,1000568931,SALUS FRUTTE MANZANA UVA 600 ML,72,36,0.50,1.00,0.50,15.0,144.00,72.00
4586,2026-04-01,2026-04-30,62,411,Express Rivera,Almacen,CABECERA MONDELEZ 1,30,COMESTIBLES,GALLETAS,...,1000055125,GALLETA RELLENA OREO REGULAR 354 GR,35,10,1.07,1.00,1.07,32.1,32.71,9.35

In [34]:
cab_view.columns

Index(['FECHA_INICIO', 'FECHA_FIN', 'GEOG_LOCL_ID', 'GEOG_LOCL_COD',
       'GEOG_LOCL_DESC', 'SECCION', 'PUNTERA', 'DURACION_PUNTERA', 'GRUPO',
       'DEPT', 'CLASE', 'SUBCLASE', 'ITEM', 'ARTC_ARTC_DESC',
       'CANT_MAX_X_ESTANTE', 'CANT_MIN_X_ESTANTE', 'VENTA_BASAL',
       'ACELERACION', 'VENTA_ACELERADA_DIARIA', 'CARGA_SUGERIDA_X_VENTA',
       'DOH_CARGA_MAX', 'DOH_CARGA_MIN'],
      dtype='object')

In [41]:
m = cab_view.merge(cab_base, how='left', on=['FECHA_INICIO', 'FECHA_FIN', 'GEOG_LOCL_ID', 'GEOG_LOCL_COD',
       'GEOG_LOCL_DESC', 'SECCION', 'PUNTERA', 'DURACION_PUNTERA', 'GRUPO',
       'DEPT', 'CLASE', 'SUBCLASE', 'ITEM', 'ARTC_ARTC_DESC',
       'CANT_MAX_X_ESTANTE', 'CANT_MIN_X_ESTANTE', 'VENTA_BASAL'], indicator=True)
print(m[m['_merge']!='both'].shape)
m[m['_merge']!='both'].iloc[:,:20]

(5, 28)

,FECHA_INICIO,FECHA_FIN,GEOG_LOCL_ID,GEOG_LOCL_COD,GEOG_LOCL_DESC,SECCION,PUNTERA,DURACION_PUNTERA,GRUPO,DEPT,CLASE,SUBCLASE,ITEM,ARTC_ARTC_DESC,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,VENTA_BASAL,ACELERACION_x,VENTA_ACELERADA_DIARIA_x,CARGA_SUGERIDA_X_VENTA_x
1908,2026-04-01,2026-04-30,16,147,Super Rocha,PyL,ISLAS LEVER NEGO ABRIL,30,PERFUMERIA,CUIDADO DE BEBES,PANALES DE BEBES,PANALES ECONOMY,1000555462,HUGGIES PA?AL FLEX COMFORT 50 UDD + TOALLITA H...,5,5,NaN,1.00,NaN,NaN
3151,2026-04-01,2026-04-30,303,168,Hiper Paseo del Este,Bebidas,CABECERA 3 SALUS,30,BEBIDAS,BEB. NO ALCOHOLICAS,AGUAS,SABORIZADAS SIN GAS,1000049624,AGUA SABORIZADA SALUS FRUTTE LIMONADA SIN GAS ...,5,5,NaN,1.07,NaN,NaN
4352,2026-04-01,2026-04-30,97,330,Super San Jose Mvd,Bebidas,CABECERA 5 PERNOD,30,BEBIDAS,BEB. ALCOHOLICAS,APERITIVOS,FERNET,1000461360,FERNET BUHERO NEGRO 700 ML,39,26,NaN,1.41,NaN,NaN
4559,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Almacen,CABECERAS LESTONSUR,30,COMESTIBLES,GALLETAS,DULCES,NO RELLENAS,1000571283,COOKIES PUNTA BALLENA CON GRAJEAS JOAQUINA 150 GR,42,42,NaN,1.00,NaN,NaN
4560,2026-04-01,2026-04-30,102,335,Super Fondar (Trinidad),Almacen,CABECERAS LESTONSUR,30,COMESTIBLES,GALLETAS,DULCES,NO RELLENAS,1000555307,COOKIES PUNTA BALLENA LUA 150 GR,42,42,NaN,1.00,NaN,NaN

In [50]:
m['DIF_AC'] = 100*(m['ACELERACION_x'] - m['ACELERACION_y'])/m['ACELERACION_x']
m['DIF_VA'] = 100*(m['VENTA_ACELERADA_DIARIA_x'] - m['VENTA_ACELERADA_DIARIA_y'])/m['VENTA_ACELERADA_DIARIA_x']
m['DIF_CS'] = 100*(m['CARGA_SUGERIDA_X_VENTA_x'] - m['CARGA_SUGERIDA_X_VENTA_y'])/m['CARGA_SUGERIDA_X_VENTA_x']
m['DIF_DOH_MIN'] = 100*(m['DOH_CARGA_MIN_x'] - m['DOH_CARGA_MIN_y'])/m['DOH_CARGA_MIN_x']
m['DIF_DOH_MAX'] = 100*(m['DOH_CARGA_MAX_x'] - m['DOH_CARGA_MAX_y'])/m['DOH_CARGA_MAX_x']
print(m['DIF_AC'].max())
print(m['DIF_VA'].max())
print(m['DIF_CS'].max())
print(m['DIF_DOH_MIN'].max())
print(m['DIF_DOH_MAX'].max())

0.8333333333333341
0.9852216748768483
0.9852216748768496
0.8064516129032265
0.8064516129032265

In [44]:
cab_base[(cab_base['GEOG_LOCL_COD']==168) & (cab_base['ITEM'].isin([1000049624]))]

Empty DataFrame
Columns: [FECHA_INICIO, FECHA_FIN, GEOG_LOCL_ID, GEOG_LOCL_COD, GEOG_LOCL_DESC, SECCION, PUNTERA, DURACION_PUNTERA, GRUPO, DEPT, CLASE, SUBCLASE, ITEM, ARTC_ARTC_DESC, CANT_MAX_X_ESTANTE, CANT_MIN_X_ESTANTE, VENTA_BASAL, ACELERACION, VENTA_ACELERADA_DIARIA, CARGA_SUGERIDA_X_VENTA, DOH_CARGA_MAX, DOH_CARGA_MIN]
Index: []

[0 rows x 22 columns]

In [43]:
cab_view[(cab_view['GEOG_LOCL_COD']==147) & (cab_view['ITEM'].isin([1000555462]))]

,FECHA_INICIO,FECHA_FIN,GEOG_LOCL_ID,GEOG_LOCL_COD,GEOG_LOCL_DESC,SECCION,PUNTERA,DURACION_PUNTERA,GRUPO,DEPT,...,ITEM,ARTC_ARTC_DESC,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,VENTA_BASAL,ACELERACION,VENTA_ACELERADA_DIARIA,CARGA_SUGERIDA_X_VENTA,DOH_CARGA_MAX,DOH_CARGA_MIN
1908,2026-04-01,2026-04-30,16,147,Super Rocha,PyL,ISLAS LEVER NEGO ABRIL,30,PERFUMERIA,CUIDADO DE BEBES,...,1000555462,HUGGIES PA?AL FLEX COMFORT 50 UDD + TOALLITA H...,5,5,NaN,1.0,NaN,NaN,1000.0,1000.0

In [2]:
#Conectamos a snowflake
credentials_snowflake = get_credentials("snow")

In [3]:
user, cursor, snow = snowflake_login(
                                    user = credentials_snowflake['USER'],
                                    password = credentials_snowflake['PASS'],
                                    account = credentials_snowflake['ACCOUNT']
                                    )

Intento 1

2026-03-16 15:33:48.220
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\marcos.larran\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

Correct Password - connected to SNOWFLAKE

In [5]:
cursor.execute("SELECT * FROM SANDBOX_PLUS.DWH.INPUT_PUNTERAS WHERE FECHA_INICIO = '2026-02-01' AND UPPER(PUNTERA) NOT LIKE '%EX%BI%' AND SECCION<>'NF';")
punt = cursor.fetch_pandas_all()
punt.columns

Index(['PUNTERA', 'ESTADISTICO', 'ITEM', 'DESCRIPCION', 'LOCAL',
       'FECHA_INICIO', 'FECHA_FIN', 'SECCION'],
      dtype='object')

In [1]:
import pandas as pd

def add_date_blocks(df, date_column):
    # Ensure date column is in datetime format and sorted
    df = df.copy()
    df[date_column] = pd.to_datetime(df[date_column])
    df = df.sort_values(by=date_column).reset_index(drop=True)
    
    # Find gaps between consecutive dates
    df['date_diff'] = df[date_column].diff().dt.days.fillna(1)
    
    # Create a group whenever there's a gap
    df['group'] = (df['date_diff'] > 1).cumsum()
    
    # Get beginning and end for each group
    group_ranges = df.groupby('group')[date_column].agg(beginning='min', end='max')
    
    # Merge the group ranges back into the original dataframe
    df = df.merge(group_ranges, on='group', how='left')
    
    # Drop helper columns
    df = df.drop(columns=['date_diff', 'group'])
    
    return df

In [8]:
data = {
    'date': ['2025-01-01', '2025-01-02', '2025-01-04', '2025-01-06', '2025-01-05'],
    'value': [10, 20, 30, 40, 50], 'value2': [11, 19, 30, 42, 45]
}

df = pd.DataFrame(data)
# result = add_date_blocks(df, 'date')
# print(result)
df

         date  value  value2
0  2025-01-01     10      11
1  2025-01-02     20      19
2  2025-01-04     30      30
3  2025-01-06     40      42
4  2025-01-05     50      45

In [16]:
df = pd.read_excel('Hiper Cordon (3).xlsx').astype({'Orin':'str'})
df

,Fecha desde,Fecha hasta,Local,Sector,Tipo,Numerador,Orin,Prioridad,Costo,Precio,Descripción,Departamento,Tipo negociación,Carga sugerida,Porcentaje participación
0,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000051395,1,1.00,1.0,ADEREZO MAYONESA HELLMANN'S 500 GR,ADEREZOS,Contrato anual,60.0,20.0
1,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000453920,1,1.00,1.0,ADEREZO MAYONESA HELLMANNS AHUMADA 340 GR,ADEREZOS,Contrato anual,24.0,20.0
2,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000511189,1,1.00,1.0,ADEREZO MAYONESA PICANTE HELLMANNS 340 GR,ADEREZOS,Contrato anual,24.0,20.0
3,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000453919,1,1.00,1.0,ADEREZO MAYONESA HELLMANNS AJO 340 GR,ADEREZOS,Contrato anual,24.0,20.0
4,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000051391,1,1.00,1.0,ADEREZO MAYONESA HELLMANN'S LIGHT 500 GR,ADEREZOS,Contrato anual,60.0,20.0
5,2026-02-01,2026-02-28,101,ALM,Puntera,2,1000055125,1,1.00,1.0,GALLETA RELLENA OREO REGULAR 354 GR,GALLETAS,Contrato anual,50.0,10.0
6,2026-02-01,2026-02-28,101,ALM,Puntera,3,1000052980,1,135.63,230.0,DORITOS LAYS QUESO 235 G,SNACKS,Contrato anual,20.0,0.0
7,2026-02-01,2026-02-28,101,ALM,Puntera,3,1000454086,1,135.63,230.0,PAPAS FRITAS LAYS CLASICAS 235 GR,SNACKS,Contrato anual,20.0,0.0
8,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056144,1,1.00,1.0,PAN TORTUGA LOS SORCHANTES CLASICO 6 UD,PANIFICADOS,Contrato anual,40.0,1.0
9,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056128,1,1.00,1.0,PAN DE VIENA LOS SORCHANTES 210 GR,PANIFICADOS,Contrato anual,40.0,1.0
10,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056111,1,1.00,1.0,PAN INTEGRAL LOS SORCHANTES FAMILIAR 550 GR,PANIFICADOS,Contrato anual,40.0,1.0
11,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056104,1,1.00,1.0,PAN AMERICANO LOS SORCHANTES 480 GR,PANIFICADOS,Contrato anual,40.0,1.0
12,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000053371,1,1.00,1.0,ALIMENTO ACHOCOLATADO VASCOLET OPTI 500 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0
13,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000198437,1,1.00,1.0,CAFE SOLUBLE BRACAFE SACHET 170 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0
14,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000052611,1,1.00,1.0,CEREAL NESQUIK CHOCOLATE 90 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0
15,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000052614,1,1.00,1.0,CEREALES TRIX NESTLE FRUTAS 90 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0
16,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000299401,1,1.00,1.0,GALLETAS 9 DE ORO AGRIDULCES 100 GR,GALLETAS,Contrato anual,40.0,1.0
17,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000524794,1,1.00,1.0,PEPAS CON MEMBRILLO DULCE MAMA 140 GR,GALLETAS,Contrato anual,40.0,1.0
18,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000555993,1,1.00,1.0,BIZCOCHOS 9 DE ORO CLASICOS 200 GR,GALLETAS,Contrato anual,40.0,1.0
19,NaT,NaT,101,ALM,Puntera,7,0,0,0.00,0.0,NaN,NaN,NaN,NaN,0.0

In [17]:
df.columns = df.columns.str.upper()
df['PUNTERA'] = df['SECTOR'].astype('str') + df['NUMERADOR'].astype('str')
df

,FECHA DESDE,FECHA HASTA,LOCAL,SECTOR,TIPO,NUMERADOR,ORIN,PRIORIDAD,COSTO,PRECIO,DESCRIPCIÓN,DEPARTAMENTO,TIPO NEGOCIACIÓN,CARGA SUGERIDA,PORCENTAJE PARTICIPACIÓN,PUNTERA
0,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000051395,1,1.00,1.0,ADEREZO MAYONESA HELLMANN'S 500 GR,ADEREZOS,Contrato anual,60.0,20.0,ALM1
1,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000453920,1,1.00,1.0,ADEREZO MAYONESA HELLMANNS AHUMADA 340 GR,ADEREZOS,Contrato anual,24.0,20.0,ALM1
2,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000511189,1,1.00,1.0,ADEREZO MAYONESA PICANTE HELLMANNS 340 GR,ADEREZOS,Contrato anual,24.0,20.0,ALM1
3,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000453919,1,1.00,1.0,ADEREZO MAYONESA HELLMANNS AJO 340 GR,ADEREZOS,Contrato anual,24.0,20.0,ALM1
4,2026-02-01,2026-02-28,101,ALM,Puntera,1,1000051391,1,1.00,1.0,ADEREZO MAYONESA HELLMANN'S LIGHT 500 GR,ADEREZOS,Contrato anual,60.0,20.0,ALM1
5,2026-02-01,2026-02-28,101,ALM,Puntera,2,1000055125,1,1.00,1.0,GALLETA RELLENA OREO REGULAR 354 GR,GALLETAS,Contrato anual,50.0,10.0,ALM2
6,2026-02-01,2026-02-28,101,ALM,Puntera,3,1000052980,1,135.63,230.0,DORITOS LAYS QUESO 235 G,SNACKS,Contrato anual,20.0,0.0,ALM3
7,2026-02-01,2026-02-28,101,ALM,Puntera,3,1000454086,1,135.63,230.0,PAPAS FRITAS LAYS CLASICAS 235 GR,SNACKS,Contrato anual,20.0,0.0,ALM3
8,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056144,1,1.00,1.0,PAN TORTUGA LOS SORCHANTES CLASICO 6 UD,PANIFICADOS,Contrato anual,40.0,1.0,ALM4
9,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056128,1,1.00,1.0,PAN DE VIENA LOS SORCHANTES 210 GR,PANIFICADOS,Contrato anual,40.0,1.0,ALM4
10,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056111,1,1.00,1.0,PAN INTEGRAL LOS SORCHANTES FAMILIAR 550 GR,PANIFICADOS,Contrato anual,40.0,1.0,ALM4
11,2026-02-01,2026-02-28,101,ALM,Puntera,4,1000056104,1,1.00,1.0,PAN AMERICANO LOS SORCHANTES 480 GR,PANIFICADOS,Contrato anual,40.0,1.0,ALM4
12,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000053371,1,1.00,1.0,ALIMENTO ACHOCOLATADO VASCOLET OPTI 500 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0,ALM5
13,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000198437,1,1.00,1.0,CAFE SOLUBLE BRACAFE SACHET 170 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0,ALM5
14,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000052611,1,1.00,1.0,CEREAL NESQUIK CHOCOLATE 90 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0,ALM5
15,2026-02-01,2026-02-28,101,ALM,Puntera,5,1000052614,1,1.00,1.0,CEREALES TRIX NESTLE FRUTAS 90 GR,DESAYUNO Y MERIENDA,Contrato anual,40.0,1.0,ALM5
16,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000299401,1,1.00,1.0,GALLETAS 9 DE ORO AGRIDULCES 100 GR,GALLETAS,Contrato anual,40.0,1.0,ALM6
17,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000524794,1,1.00,1.0,PEPAS CON MEMBRILLO DULCE MAMA 140 GR,GALLETAS,Contrato anual,40.0,1.0,ALM6
18,2026-02-01,2026-02-28,101,ALM,Puntera,6,1000555993,1,1.00,1.0,BIZCOCHOS 9 DE ORO CLASICOS 200 GR,GALLETAS,Contrato anual,40.0,1.0,ALM6
19,NaT,NaT,101,ALM,Puntera,7,0,0,0.00,0.0,NaN,NaN,NaN,NaN,0.0,ALM7

In [18]:
tuple(df['ORIN'].unique())

('1000051395',
 '1000453920',
 '1000511189',
 '1000453919',
 '1000051391',
 '1000055125',
 '1000052980',
 '1000454086',
 '1000056144',
 '1000056128',
 '1000056111',
 '1000056104',
 '1000053371',
 '1000198437',
 '1000052611',
 '1000052614',
 '1000299401',
 '1000524794',
 '1000555993',
 '0')

In [19]:
art = descargar_segmento(cursor=cursor, query='ARTICULOS', cond=tuple(df['ORIN'].unique()))
art

,ARTC_ARTC_ID,ORIN,ARTC_ARTC_COD,ARTC_ARTC_DESC
0,297365,1000453919,254674000,ADEREZO MAYONESA HELLMANNS AJO 340 GR
1,297406,1000453920,254700000,ADEREZO MAYONESA HELLMANNS AHUMADA 340 GR
2,20237,1000052614,253542000,CEREALES TRIX NESTLE FRUTAS 90 GR
3,20231,1000052611,253535000,CEREAL NESQUIK CHOCOLATE 90 GR
4,232787,1000198437,251968000,CAFE SOLUBLE BRACAFE SACHET 170 GR
5,11341400,1000524794,262384000,PEPAS CON MEMBRILLO DULCE MAMA 140 GR
6,6534405,1000511189,255300000,ADEREZO MAYONESA PICANTE HELLMANNS 340 GR
7,15687340,1000555993,262422000,BIZCOCHOS 9 DE ORO CLASICOS 200 GR
8,77279,1000056111,266111000,PAN INTEGRAL LOS SORCHANTES FAMILIAR 550 GR
9,77272,1000056104,266104000,PAN AMERICANO LOS SORCHANTES 480 GR
10,96902,1000056144,266176000,PAN TORTUGA LOS SORCHANTES CLASICO 6 UD
11,170145,1000052980,254249000,DORITOS LAYS QUESO 235 G
12,77252,1000053371,255925000,ALIMENTO ACHOCOLATADO VASCOLET OPTI 500 GR
13,106096,1000055125,261007000,GALLETA RELLENA OREO REGULAR 354 GR
14,19453,1000051395,251811000,ADEREZO MAYONESA HELLMANN'S 500 GR
15,19451,1000051391,251807000,ADEREZO MAYONESA HELLMANN'S LIGHT 500 GR
16,297447,1000454086,254717000,PAPAS FRITAS LAYS CLASICAS 235 GR
17,95245,1000056128,266142000,PAN DE VIENA LOS SORCHANTES 210 GR
18,248378,1000299401,262019000,GALLETAS 9 DE ORO AGRIDULCES 100 GR

In [25]:
#Armammos df de puntera
punt = df.merge(art)[['PUNTERA', 'ARTC_ARTC_COD', 'ORIN', 'ARTC_ARTC_DESC', 'LOCAL', 'FECHA DESDE',
                      'FECHA HASTA', 'SECTOR']]
punt.columns = ['PUNTERA', 'ESTADISTICO', 'ITEM', 'DESCRIPCION',
                'LOCAL', 'FECHA_INICIO', 'FECHA_FIN', 'SECCION']
punt['KEY'] = punt['LOCAL'].astype('str') + ' ' + punt['ITEM']
punt

,PUNTERA,ESTADISTICO,ITEM,DESCRIPCION,LOCAL,FECHA_INICIO,FECHA_FIN,SECCION,KEY
0,ALM1,251811000,1000051395,ADEREZO MAYONESA HELLMANN'S 500 GR,101,2026-02-01,2026-02-28,ALM,101 1000051395
1,ALM1,254700000,1000453920,ADEREZO MAYONESA HELLMANNS AHUMADA 340 GR,101,2026-02-01,2026-02-28,ALM,101 1000453920
2,ALM1,255300000,1000511189,ADEREZO MAYONESA PICANTE HELLMANNS 340 GR,101,2026-02-01,2026-02-28,ALM,101 1000511189
3,ALM1,254674000,1000453919,ADEREZO MAYONESA HELLMANNS AJO 340 GR,101,2026-02-01,2026-02-28,ALM,101 1000453919
4,ALM1,251807000,1000051391,ADEREZO MAYONESA HELLMANN'S LIGHT 500 GR,101,2026-02-01,2026-02-28,ALM,101 1000051391
5,ALM2,261007000,1000055125,GALLETA RELLENA OREO REGULAR 354 GR,101,2026-02-01,2026-02-28,ALM,101 1000055125
6,ALM3,254249000,1000052980,DORITOS LAYS QUESO 235 G,101,2026-02-01,2026-02-28,ALM,101 1000052980
7,ALM3,254717000,1000454086,PAPAS FRITAS LAYS CLASICAS 235 GR,101,2026-02-01,2026-02-28,ALM,101 1000454086
8,ALM4,266176000,1000056144,PAN TORTUGA LOS SORCHANTES CLASICO 6 UD,101,2026-02-01,2026-02-28,ALM,101 1000056144
9,ALM4,266142000,1000056128,PAN DE VIENA LOS SORCHANTES 210 GR,101,2026-02-01,2026-02-28,ALM,101 1000056128
10,ALM4,266111000,1000056111,PAN INTEGRAL LOS SORCHANTES FAMILIAR 550 GR,101,2026-02-01,2026-02-28,ALM,101 1000056111
11,ALM4,266104000,1000056104,PAN AMERICANO LOS SORCHANTES 480 GR,101,2026-02-01,2026-02-28,ALM,101 1000056104
12,ALM5,255925000,1000053371,ALIMENTO ACHOCOLATADO VASCOLET OPTI 500 GR,101,2026-02-01,2026-02-28,ALM,101 1000053371
13,ALM5,251968000,1000198437,CAFE SOLUBLE BRACAFE SACHET 170 GR,101,2026-02-01,2026-02-28,ALM,101 1000198437
14,ALM5,253535000,1000052611,CEREAL NESQUIK CHOCOLATE 90 GR,101,2026-02-01,2026-02-28,ALM,101 1000052611
15,ALM5,253542000,1000052614,CEREALES TRIX NESTLE FRUTAS 90 GR,101,2026-02-01,2026-02-28,ALM,101 1000052614
16,ALM6,262019000,1000299401,GALLETAS 9 DE ORO AGRIDULCES 100 GR,101,2026-02-01,2026-02-28,ALM,101 1000299401
17,ALM6,262384000,1000524794,PEPAS CON MEMBRILLO DULCE MAMA 140 GR,101,2026-02-01,2026-02-28,ALM,101 1000524794
18,ALM6,262422000,1000555993,BIZCOCHOS 9 DE ORO CLASICOS 200 GR,101,2026-02-01,2026-02-28,ALM,101 1000555993

In [27]:
tuple(punt['KEY'].unique())

('101 1000051395',
 '101 1000453920',
 '101 1000511189',
 '101 1000453919',
 '101 1000051391',
 '101 1000055125',
 '101 1000052980',
 '101 1000454086',
 '101 1000056144',
 '101 1000056128',
 '101 1000056111',
 '101 1000056104',
 '101 1000053371',
 '101 1000198437',
 '101 1000052611',
 '101 1000052614',
 '101 1000299401',
 '101 1000524794',
 '101 1000555993')

In [29]:
'SELECT * FROM SANDBOX_PLUS.DWH.CABECERAS_BASE WHERE CONCAT(GEOG_LOCL_COD::TEXT, ' ', ITEM::TEXT) IN {cond};'.format(cond=tuple(punt['KEY'].unique()))

"SELECT * FROM SANDBOX_PLUS.DWH.CABECERAS_BASE WHERE CONCAT(GEOG_LOCL_COD::TEXT, , ITEM::TEXT) IN ('101 1000051395', '101 1000453920', '101 1000511189', '101 1000453919', '101 1000051391', '101 1000055125', '101 1000052980', '101 1000454086', '101 1000056144', '101 1000056128', '101 1000056111', '101 1000056104', '101 1000053371', '101 1000198437', '101 1000052611', '101 1000052614', '101 1000299401', '101 1000524794', '101 1000555993');"

In [ ]:
cursor.execute("SELECT * FROM SANDBOX_PLUS.DWH.CABECERAS_BASE WHERE CONCAT(GEOG_LOCL_COD::TEXT, ' ', ITEM::TEXT) IN {cond};".format(cond=tuple(punt['KEY'].unique())))
cab = cursor.fetch_pandas_all()
cab

,GEOG_LOCL_ID,GEOG_LOCL_COD,GEOG_LOCL_DESC,GRUPO,DEPT,CLASE,SUBCLASE,ITEM,ARTC_ARTC_DESC,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,VENTA_BASAL,ACELERACION,VENTA_ACELERADA_DIARIA,DOH_CARGA_MAX,DOH_CARGA_MIN
0,21,101,Hiper Cordon,COMESTIBLES,PANIFICADOS,PAN DE MESA,PAN DE MOLDE REGULAR,1000056104,PAN AMERICANO LOS SORCHANTES 480 GR,13.0,13.0,50.57,1.04,52.59,0.25,0.25
1,21,101,Hiper Cordon,COMESTIBLES,GALLETAS,DULCES,NO RELLENAS,1000524794,PEPAS CON MEMBRILLO DULCE MAMA 140 GR,60.0,20.0,14.65,4.34,63.58,0.94,0.31
2,21,101,Hiper Cordon,COMESTIBLES,PANIFICADOS,PAN DE MESA,PAN DE MOLDE INTEGRAL,1000056111,PAN INTEGRAL LOS SORCHANTES FAMILIAR 550 GR,13.0,13.0,12.37,1.09,13.48,0.96,0.96
3,21,101,Hiper Cordon,COMESTIBLES,GALLETAS,DULCES,ARTESANALES DULCES,1000299401,GALLETAS 9 DE ORO AGRIDULCES 100 GR,100.0,20.0,35.02,1.68,58.83,1.70,0.34
4,21,101,Hiper Cordon,COMESTIBLES,SNACKS,SNACKS DE MAIZ,SNACKS TORTILLAS,1000052980,DORITOS LAYS QUESO 235 G,18.0,12.0,3.33,1.25,4.16,4.33,2.88
5,21,101,Hiper Cordon,COMESTIBLES,SNACKS,PAPAS FRITAS,PAPAS FRITAS EN BOLSA,1000454086,PAPAS FRITAS LAYS CLASICAS 235 GR,18.0,12.0,2.18,1.78,3.88,4.64,3.09
6,21,101,Hiper Cordon,COMESTIBLES,PANIFICADOS,BOLLERIA,TORTUGA,1000056144,PAN TORTUGA LOS SORCHANTES CLASICO 6 UD,28.0,8.0,2.98,1.20,3.58,7.82,2.23
7,21,101,Hiper Cordon,COMESTIBLES,PANIFICADOS,BOLLERIA,VIENA,1000056128,PAN DE VIENA LOS SORCHANTES 210 GR,40.0,10.0,4.69,1.08,5.07,7.89,1.97
8,21,101,Hiper Cordon,COMESTIBLES,GALLETAS,DULCES,RELLENA,1000055125,GALLETA RELLENA OREO REGULAR 354 GR,35.0,10.0,3.46,1.13,3.91,8.95,2.56
9,21,101,Hiper Cordon,COMESTIBLES,ADEREZOS,MAYONESA,MAYONESA TRADICIONAL,1000051395,ADEREZO MAYONESA HELLMANN'S 500 GR,50.0,20.0,3.60,1.53,5.51,9.07,3.63
10,21,101,Hiper Cordon,COMESTIBLES,ADEREZOS,MAYONESA,MAYONESA LIGHT,1000051391,ADEREZO MAYONESA HELLMANN'S LIGHT 500 GR,66.0,22.0,3.92,1.20,4.70,14.04,4.68
11,21,101,Hiper Cordon,COMESTIBLES,DESAYUNO Y MERIENDA,CEREALES,CEREALES CON SABORES,1000052614,CEREALES TRIX NESTLE FRUTAS 90 GR,70.0,20.0,1.84,2.06,3.79,18.47,5.28
12,21,101,Hiper Cordon,COMESTIBLES,DESAYUNO Y MERIENDA,CHOCOLATES DESAYUNO,POLVO ACHOCOLATADO,1000053371,ALIMENTO ACHOCOLATADO VASCOLET OPTI 500 GR,44.0,22.0,0.88,1.43,1.26,34.92,17.46
13,21,101,Hiper Cordon,COMESTIBLES,DESAYUNO Y MERIENDA,CAFE,SOLUBLE,1000198437,CAFE SOLUBLE BRACAFE SACHET 170 GR,91.0,26.0,1.34,1.41,1.89,48.15,13.76
14,21,101,Hiper Cordon,COMESTIBLES,DESAYUNO Y MERIENDA,CEREALES,CEREALES CON SABORES,1000052611,CEREAL NESQUIK CHOCOLATE 90 GR,70.0,20.0,0.53,1.79,0.95,73.68,21.05
15,21,101,Hiper Cordon,COMESTIBLES,ADEREZOS,MAYONESA,ESPECIFICA,1000453919,ADEREZO MAYONESA HELLMANNS AJO 340 GR,96.0,32.0,1.20,0.99,1.19,80.67,26.89
16,21,101,Hiper Cordon,COMESTIBLES,ADEREZOS,MAYONESA,ESPECIFICA,1000453920,ADEREZO MAYONESA HELLMANNS AHUMADA 340 GR,96.0,32.0,1.02,1.00,1.02,94.12,31.37
17,21,101,Hiper Cordon,COMESTIBLES,ADEREZOS,MAYONESA,ESPECIALIDADES,1000511189,ADEREZO MAYONESA PICANTE HELLMANNS 340 GR,96.0,32.0,0.97,1.04,1.01,95.05,31.68
18,21,101,Hiper Cordon,COMESTIBLES,GALLETAS,SALADAS,ARTESANALES SALADAS,1000555993,BIZCOCHOS 9 DE ORO CLASICOS 200 GR,91.0,26.0,0.12,1.00,0.12,758.33,216.67

In [12]:
df['flag_carga_min'] = (df['CARGA_SUGERIDA_X_VENTA']<=df['CARGA_MIN_POR_PARTICIPACION']).astype('int64')
# df['flag_carga_max'] = (df['CARGA_SUGERIDA_X_VENTA']>=df['CARGA_MAX_POR_PARTICIPACION']).astype('int64')
df[['GEOG_LOCL_COD', 'ITEM', 'CANT_MAX_X_ESTANTE', 'CANT_MIN_X_ESTANTE', 'PARTICIPACION',
   'CARGA_SUGERIDA_X_VENTA', 'CARGA_MAX_POR_PARTICIPACION', 'CARGA_MIN_POR_PARTICIPACION']]

,GEOG_LOCL_COD,ITEM,CANT_MAX_X_ESTANTE,CANT_MIN_X_ESTANTE,PARTICIPACION,CARGA_SUGERIDA_X_VENTA,CARGA_MAX_POR_PARTICIPACION,CARGA_MIN_POR_PARTICIPACION
0,101,1000055125,35.0,10.0,5.0,109.0,175.0,50.0
1,102,1000055125,35.0,10.0,5.0,47.0,175.0,50.0
2,103,1000055125,35.0,10.0,5.0,174.0,175.0,50.0
3,104,1000055125,35.0,10.0,5.0,108.0,175.0,50.0
4,107,1000055125,35.0,10.0,5.0,83.0,175.0,50.0
...,...,...,...,...,...,...,...,...
99,333,1000290455,48.0,32.0,2.0,85.0,96.0,64.0
100,333,1000055019,48.0,32.0,2.0,83.0,96.0,64.0
101,333,1000054947,48.0,12.0,1.0,4.0,48.0,12.0
102,334,1000055125,35.0,10.0,5.0,122.0,175.0,50.0
103,335,1000055125,35.0,10.0,5.0,25.0,175.0,50.0

In [3]:
df.to_csv('../../df.csv', index=False, sep= ";")

In [22]:
locales = pd.read_csv('C:/Users/marcos.larran/Downloads/LOCALES.csv')
locales

     GEOG_LOCL_ID  CODIGO_TIENDA
0               8            132
1               9            134
2              11            140
3              12            143
4              13            144
..            ...            ...
240           333            450
241           334            451
242           335            452
243           336            454
244           337            453

[245 rows x 2 columns]

In [2]:
nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/Nielsen viejo.csv')
nielsen

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,PRIORIDAD,GEOG_LOCL_ID
0,100356243,DEVOTO EXPRESS SUC. 3113 SARANDI 690 A JUNCAL ...,S R NDI 690- JUNC L 1347 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,6,21
1,100356250,DEVOTO EXPRESS SUC. 3121 CANELONES 1251 ESQ. C...,C NELONES 1251 ESQ C QUIJ NO NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,7,21
2,100356180,DISCO SUC. 117 MALDONADO 1024 SUR GRANMONTEVIDEO,M LDON DO-1024-SUR NN,GRAN MONTEVIDEO B,MONTEVIDEO,BARRIO SUR,DISCO,DISCO,101,9,21
3,100356170,DISCO SUC. 103 ARENAL GDE. 1376 CORDON GRANMON...,REN L GDE-1376-CORDON NN,GRAN MONTEVIDEO B,MONTEVIDEO,CORDON,DISCO,DISCO,101,10,21
4,100356367,DEVOTO EXPRESS SUC. 3132 SAN JOSE 1085 / 1087 0,S N JOSE 1085 / 1087 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,8,21
...,...,...,...,...,...,...,...,...,...,...,...
430,100356186,DISCO SUC. 125 MCAL. SOLANO LOPEZ 1680 0,NN NN,GRAN MONTEVIDEO A,MONTEVIDEO,BUCEO,DISCO,DISCO,420,3,322
431,100356252,DEVOTO EXPRESS SUC. 3124 CNO. CARRASCO 6955 SE...,CNO C RR SCO 6955 NN,GRAN MONTEVIDEO A,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,420,2,322
432,100356159,TIENDA INGLESA SUC. 1 AV. ITALIA ESQ. BOLIVIA ...,V IT LI--ESQ BOLIVI- 5820-M LVIN NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,4,322
433,100356160,TIENDA INGLESA SUC. 2 SCHROEDER 6436 CARRASCO ...,SCHROEDER- 6436-C RR SCO NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,5,322
434,100356201,DEVOTO SUC. 3003 AV. GRAL RIVERA 4502 BRISAS G...,V GR L RIVER- 4502-BRIS S NN,GRAN MONTEVIDEO A,MONTEVIDEO,MALVIN,DEVOTO,DEVOTO,420,1,322

In [23]:
c_nielsen = pd.read_excel('C:/Users/marcos.larran/Downloads/correcciones Nielsen.xlsx')
print(c_nielsen.shape)
c_nielsen

(21, 2)

    CODIGO_TIENDA   STORE_ID
0             143  108282396
1             111  108282396
2             156  108282396
3             316  108282396
4             145  100356446
5             335  100356446
6             139  100356353
7             139  106558845
8             155  100356353
9             155  106558845
10            126  100356353
11            126  106558845
12            331  100356353
13            331  106558845
14            332  100356353
15            332  106558845
16            333  100356353
17            333  106558845
18            417  100356206
19            417  100356211
20            417  100356246

In [16]:
info_nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/PriceMaster_UY_grupo_tata.csv',
                           encoding='ISO-8859-1', sep='|')
info_nielsen = info_nielsen[['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA',
                             'CITY', 'RETAILER', 'BANNER']].drop_duplicates()
info_nielsen

C:\Users\marcos.larran\AppData\Local\Temp\ipykernel_22396\395866159.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  info_nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/PriceMaster_UY_grupo_tata.csv',

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER
0,100356162,TIENDA INGLESA SUC. 4 J.B. BLANCO 966 POCITOS ...,JB BL NCO- 966-POCITOS NN,GRAN MONTEVIDEO A,MONTEVIDEO,POCITOS,TIENDA INGLESA,TIENDA INGLESA
163,100356169,DISCO SUC. 102 AV. AGRACIADA 2986 PRADO GRANMO...,V-GR CI D- 2986-PR DO NN,GRAN MONTEVIDEO B,MONTEVIDEO,CAPURRO,DISCO,DISCO
708,100356175,DISCO SUC. 111 8 DE OCTUBRE 2681 TRES CRUCES G...,8 DE OCTUBRE- 2681-TRES CRUCES NN,GRAN MONTEVIDEO B,MONTEVIDEO,PQE BATTLE,DISCO,DISCO
798,100356176,DISCO SUC. 112 8 DE OCTUBRE 4786 UNION GRANMON...,8 DE OCTUBRE-4786-UNION NN,GRAN MONTEVIDEO B,MONTEVIDEO,MARONAS,DISCO,DISCO
1230,100356177,DISCO SUC. 113 CHUCARRO 1320 POCITOS GRANMONTE...,CHUC RRO-1320-POCITOS NN,GRAN MONTEVIDEO A,MONTEVIDEO,POCITOS,DISCO,DISCO
...,...,...,...,...,...,...,...,...
1441042,245853700,EL DORADOSUC 2510DR MORQUIO 600 ESQUINA EUSEBI...,DR MORQUIO 600 ESQUINA EUSEBIO PIREZ NN,INTERIOR CENTRO,DURAZNO,NaN,EL DORADO,EL DORADO
1445679,245853701,EL DORADOSUC 57019 DE ABRIL Y GRAL ARTIGASAMAL...,19 DE ABRIL Y GRAL ARTIGASA NN,INTERIOR ESTE,MALDONADO,NaN,EL DORADO,EL DORADO
1461395,287358763,EL DORADOSUC 2320ÿESPINILLO Y CORONILLAÿFRAY B...,ÿESPINILLO Y CORONILLAÿ NN,INTERIOR LITORAL,RIO NEGRO,NaN,EL DORADO,EL DORADO
1461452,288159883,TATASUC 420GENERAL FLORES 2928MONTEVIDEO,GENERAL FLORES 2928 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,TATA,TATA
1461593,305903691,TIENDA INGLESASUC 450AV FRANCISCA FAJARDO Y RA...,AV FRANCISCA FAJARDO Y RAFAEL BARRADAS NN,PUNTA DEL ESTE,MALDONADO,NaN,TIENDA INGLESA,TIENDA INGLESA

In [20]:
info_nielsen['STORE_ID'].value_counts()

STORE_ID
100356162    1
100356449    1
100356445    1
100356444    1
100356443    1
            ..
100356145    1
100356141    1
100356206    1
100356205    1
305903691    1
Name: count, Length: 328, dtype: int64

In [24]:
nielsen_nuevo = c_nielsen.merge(info_nielsen).merge(locales)
print(nielsen_nuevo.shape)
nielsen_nuevo.head()

(21, 10)

,CODIGO_TIENDA,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,GEOG_LOCL_ID
0,143,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,12
1,111,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,2
2,156,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,47
3,316,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,83
4,145,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,14

In [25]:
nielsen.columns

Index(['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
       'RETAILER', 'BANNER', 'LOCL_COD', 'PRIORIDAD', 'GEOG_LOCL_ID'],
      dtype='object')

In [27]:
nielsen_nuevo = nielsen_nuevo[['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
                               'RETAILER', 'BANNER', 'CODIGO_TIENDA', 'GEOG_LOCL_ID']]
nielsen_nuevo.columns = ['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
                         'RETAILER', 'BANNER', 'LOCL_COD', 'GEOG_LOCL_ID']
nielsen_nuevo

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,GEOG_LOCL_ID
0,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,143,12
1,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,111,2
2,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,156,47
3,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,316,83
4,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,145,14
5,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,335,102
6,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,139,10
7,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,139,10
8,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,155,45
9,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,155,45
10,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,126,5
11,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,126,5
12,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,331,98
13,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,331,98
14,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,332,99
15,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,332,99
16,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,333,100
17,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,333,100
18,100356206,DEVOTO SUC. 3008 AV. GRAL. SAN MARTIN 3709 SAN...,V GR L S N M RTIN-3709-S N M RTIN NN,GRAN MONTEVIDEO B,MONTEVIDEO,CERRITO,DEVOTO,DEVOTO,417,66
19,100356211,DEVOTO SUC. 3016 SAN MARTIN * FOMENTO SAN MART...,S N M RTIN-FOMENTO--S N M RTIN NN,GRAN MONTEVIDEO B,MONTEVIDEO,PRADO,DEVOTO,DEVOTO,417,66
20,100356246,DEVOTO EXPRESS SUC. 3122 L. A. HERRERA 2940 SE...,L- HERRER-2940 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,417,66

In [28]:
nielsen_final = pd.concat([nielsen, nielsen_nuevo], ignore_index=True).sort_values(by=['LOCL_COD',
                                                                                       'PRIORIDAD'])
nielsen_final

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,PRIORIDAD,GEOG_LOCL_ID
7,141175690,EL DORADO SUC 2021?18 DE JULIO 2006 ESQUINA PA...,18 DE JULIO 2006 ESQUINA-PABLO DE MARIA NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,1.0,21
8,145749110,EL DORADO SUC 2022 PEATONAL SARANDI 584 MONTEV...,PEATONAL SARANDI 584 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,2.0,21
9,149665397,EL DORADO SUC 2023 18 DE JULIO 1807 MONTEVIDEO,18 DE JULIO 1807 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,3.0,21
10,164712852,EL DORADO SUC 2050 GARIBALDI 2579 MONTEVIDEO,GARIBALDI 2579 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,4.0,21
5,100573892,RED EXPRESS SUC 145 AVDA URUGUAY 1104 SECCION 106,AVDA URUGUAY 1104 NN,GRAN MONTEVIDEO B,MONTEVIDEO,MONTEVIDEO,TIENDA INGLESA,AUTOSERVICIOS TIENDA INGLESA,101,5.0,21
...,...,...,...,...,...,...,...,...,...,...,...
434,100356201,DEVOTO SUC. 3003 AV. GRAL RIVERA 4502 BRISAS G...,V GR L RIVER- 4502-BRIS S NN,GRAN MONTEVIDEO A,MONTEVIDEO,MALVIN,DEVOTO,DEVOTO,420,1.0,322
431,100356252,DEVOTO EXPRESS SUC. 3124 CNO. CARRASCO 6955 SE...,CNO C RR SCO 6955 NN,GRAN MONTEVIDEO A,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,420,2.0,322
430,100356186,DISCO SUC. 125 MCAL. SOLANO LOPEZ 1680 0,NN NN,GRAN MONTEVIDEO A,MONTEVIDEO,BUCEO,DISCO,DISCO,420,3.0,322
432,100356159,TIENDA INGLESA SUC. 1 AV. ITALIA ESQ. BOLIVIA ...,V IT LI--ESQ BOLIVI- 5820-M LVIN NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,4.0,322
433,100356160,TIENDA INGLESA SUC. 2 SCHROEDER 6436 CARRASCO ...,SCHROEDER- 6436-C RR SCO NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,5.0,322

In [30]:
nielsen_final.to_excel('NIELSEN COMPLETO.xlsx', index=False)

In [10]:
f = datetime.now().replace(day=22, hour=19, minute=25, second=41).strftime('%Y%m%d_%H%M%S')

In [3]:
user, cursor, snow = snowflake_login()

Intento 1
Error: 251005: User is empty
Incorrect Password - provide again
Intento 2
Correct Password - connected to SNOWFLAKE

In [12]:
duplicados = descargar_segmento(cursor, 'DUPLICADOS', cond="'" + f + "'")
duplicados

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [11]:
checks = descargar_segmento(cursor, query='TOTAL', cond="'" + f + "'")
checks

,ORIN,GEOG_LOCL_COD,PVP_NUEVO,EFFECTIVE_DATE,FAMILIA,INTEGRANTES_FAMILIA,CANASTA,ARTC_ARTC_DESC,ESTADO,ESTA_EN_PROMO,EXCLUIDO_COMERCIAL,PRECIO_DIFERENTE
0,1000505780,146,105,None,1000505777,3,surtido,GRISINES CRI CROC INTEGRALES EL TRIGAL 145 G,4,0,0,0
1,1000505779,168,105,None,1000505777,3,surtido,GRISINES CRI CROC CLASICOS EL TRIGAL 145 GR,4,0,0,0
2,1000504782,104,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
3,1000057500,149,690,None,1000057500,1,surtido,QUESO SBRINZ PREMIUM FARMING COPETIN 1.00 KG,4,0,0,0
4,1000504782,329,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
519,1000504782,168,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
520,1000505777,145,105,None,1000505777,3,surtido,GRISINES EL TRIGAL CRI CROC SIN SAL 145 GR,4,0,0,0
521,1000157000,146,440,None,1000157000,1,referente,JAMON COCIDO DELIZIA SARUBBI.,4,0,0,0
522,1000504782,173,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
523,1000504782,314,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1

In [14]:
final = descargar_segmento(cursor, query='FINAL', cond="'" + f + "'")
final

           ORIN CODIGO_TIENDA  PVP_NUEVO
0    1000057447           151        680
1    1000057447           157        740
2    1000057301           159        450
3    1000353250           153        310
4    1000505780           159        105
..          ...           ...        ...
390  1000057084           317        590
391  1000505780           318        105
392  1000505779           322        105
393  1000057156           323        550
394  1000505777           324        105

[395 rows x 3 columns]

In [15]:
datos = descargar_segmento(cursor, 'DATOS', cond="'" + f + "'")
datos

,ZONE_NODE_TYPE,ZONE_GROUP_ID,ZONE_ID,LOCATION,ITEM,DIFF_ID,SKULIST,LINK_CODE,CHANGE_TYPE,CHANGE_AMOUNT,...,PRICE_GUIDE_ID,EFFECTIVE_DATE,REASON_CODE,VENDOR_FUNDED_IND,FUNDING_TYPE,FUNDING_AMOUNT,FUNDING_AMOUNT_CURRENCY,FUNDING_PERCENT,DEAL_ID,DEAL_DETAIL_ID
0,0,None,None,151,1000057447,None,None,None,2,680,...,None,2025-07-23,2,0,None,None,None,None,None,None
1,0,None,None,157,1000057447,None,None,None,2,740,...,None,2025-07-23,2,0,None,None,None,None,None,None
2,0,None,None,159,1000057301,None,None,None,2,450,...,None,2025-07-23,2,0,None,None,None,None,None,None
3,0,None,None,153,1000353250,None,None,None,2,310,...,None,2025-07-23,2,0,None,None,None,None,None,None
4,0,None,None,159,1000505780,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,0,None,None,317,1000057084,None,None,None,2,590,...,None,2025-07-23,2,0,None,None,None,None,None,None
391,0,None,None,318,1000505780,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
392,0,None,None,322,1000505779,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
393,0,None,None,323,1000057156,None,None,None,2,550,...,None,2025-07-23,2,0,None,None,None,None,None,None
394,0,None,None,324,1000505777,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None

In [7]:
with open('Queries/DUPLICADOS.sql', 'r', encoding="utf8") as file: command = file.read()
command

'WITH PP AS (\nSELECT\n    DISTINCT A.CODIGO_TIENDA, B.FAMILIA, COUNT(DISTINCT A.PVP_NUEVO) AS P\nFROM\n    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A\nLEFT JOIN\n    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B\nON\n    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD\nWHERE\n    FECHA_EJECUCION = (SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)\nAND\n    TABLA={f}\nGROUP BY ALL\n)\n\nSELECT\n    A.*, B.FAMILIA, B.ARTC_ARTC_DESC, B.STCK_PRECIO_VENTA_DIA_CIVA\nFROM\n    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A\nJOIN\n    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B\nON\n    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD\nJOIN\n    PP\nON\n    A.CODIGO_TIENDA = PP.CODIGO_TIENDA AND B.FAMILIA = PP.FAMILIA AND P>1\nWHERE\n    FECHA_EJECUCION=(SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)\nAND\n    TABLA={f}\nORDER BY\n    GEOG_LOCL_COD, B.FAMILIA;'

In [8]:
cursor.execute(command.format(f=f))

In [ ]:
d = cursor.fetch_pandas_all()
d

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [5]:
c = "WHERE LGL.GEOG_LOCL_COD IN (101, 115) AND LAA.ORIN IN ('1000038127')"

In [12]:
with open('Queries/PRECIOS.sql', 'r', encoding="utf8") as file: command = file.read()
command

"WITH P AS (\nSELECT\n    ARTC_ARTC_ID, GEOG_LOCL_ID, MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_MEDIANO\nFROM\n    MSTRDB.DWH.FT_STOCK\nWHERE\n    TIEM_DIA_ID = CURRENT_DATE - 30\nGROUP BY ALL\n)\n\n, STOCK AS (\nSELECT\n    DISTINCT FS.ARTC_ARTC_ID, FS.GEOG_LOCL_ID, FS.STCK_PRECIO_VENTA_DIA_CIVA AS PVP_ACTUAL,\n    CASE\n        WHEN FCUR.ORIGIN_COUNTRY_ID = 'UYU' THEN FCUR.COSTO_UNITARIO_RMS\n        ELSE FS.STCK_COSTO_PROM_POND\n    END AS COSTO_UNITARIO,\n    COSTO_UNITARIO * ROUND(FS.STCK_PRECIO_VENTA_DIA_CIVA/FS.STCK_PRECIO_VENTA_DIA, 2) AS COSTO_UNITARIO_CON_IVA\nFROM\n    MSTRDB.DWH.FT_STOCK FS\nJOIN\n    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR\nON\n    FS.GEOG_LOCL_ID = FCUR.GEOG_LOCL_ID AND FS.ARTC_ARTC_ID = FCUR.ARTC_ARTC_ID\n    AND FCUR.TIEM_DIA_ID = (SELECT MAX(TIEM_DIA_ID) FROM MSTRDB.DWH.FT_COSTO_UNITARIO_RMS)\nWHERE\n    FS.TIEM_DIA_ID = CURRENT_DATE - 1\n)\n\nSELECT\n    LAA.ORIN, LGL.GEOG_LOCL_COD AS LOCAL, PVP_ACTUAL, PRECIO_MEDIANO, COSTO_UNITARIO_CON_IVA,\n    ROUND(DIV0(PVP_ACTUAL - COSTO_UNITARIO_CON_IVA, PVP_ACTUAL), 2) AS MARGEN\nFROM\n    STOCK AS FS\nJOIN\n    MSTRDB.DWH.LU_ARTC_ARTICULO LAA\nON\n    FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID\nJOIN\n    MSTRDB.DWH.LU_GEOG_LOCAL LGL\nON\n    FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID\nJOIN\n    P\nON\n    FS.ARTC_ARTC_ID = P.ARTC_ARTC_ID AND FS.GEOG_LOCL_ID = P.GEOG_LOCL_ID\n{cond};"

In [15]:
cursor.execute(command.format(cond=c))

In [16]:
p = cursor.fetch_pandas_all()
p

,ORIN,LOCAL,PVP_ACTUAL,PRECIO_MEDIANO,COSTO_UNITARIO_CON_IVA,MARGEN
0,1000038127,101,245.0,244.0,156.404,0.36
1,1000038127,115,198.0,244.0,156.404,0.21

In [4]:
duplicados = descargar_segmento(cursor, 'DUPLICADOS', cond=f)
duplicados

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [7]:
p = descargar_segmento(cursor, 'PRECIOS', cond=c)
p

,ORIN,LOCAL,PVP_ACTUAL,PRECIO_MEDIANO,COSTO_UNITARIO_CON_IVA,MARGEN
0,1000038127,101,245.0,244.0,156.404,0.36
1,1000038127,115,198.0,244.0,156.404,0.21

In [ ]:
filtros_posibles = {'PROMOCION':'ESTA_EN_PROMO = 0',
                    'EXCLUIDOS COMERCIAL':'EXCLUIDO_COMERCIAL = 0',
                        'ACTIVOS':'ARTC_ESTA_ID = 4',
                        'PRECIO DIFERENTE':'S.STCK_PRECIO_VENTA_DIA_CIVA <> A.PVP_NUEVO'}
filtros = []
todos_los_filtros = []
for f in filtros:
    todos_los_filtros.append(filtros_posibles[f])
if len(todos_los_filtros) > 0:
    todos_los_filtros = ' AND ' + ' AND '.join(todos_los_filtros)
else:
    todos_los_filtros = ''
todos_los_filtros

''

In [18]:
' AND '.join(todos_los_filtros)

''

In [20]:
if len(todos_los_filtros) > 0:
    todos_los_filtros = ' AND ' + ' AND '.join(todos_los_filtros)