In [1]:
import pandas as pd
import pandas as pd
from utils import snowflake_login, descargar_segmento, get_credentials, carga_snow_generic
from datetime import datetime, date
import os

In [2]:
uc = pd.read_csv(r'C:\Users\marcos.larran\Downloads\PRUEBA - MARCOS_2026-05-13-1537.csv')
costos = pd.read_csv(r'C:\Users\marcos.larran\Downloads\costos.csv', sep=';')

In [3]:
type(costos['ITEM'][0])

numpy.float64

In [4]:
type(uc['ORIN'][0])

numpy.int64

In [5]:
print(uc[(~uc['ORIN'].isin(costos['ITEM'].unique()))].shape)
print(uc[(uc['ORIN'].isin(costos['ITEM'].unique()))].shape)

(14790, 7)
(14279, 7)

In [7]:
uc[(~uc['ORIN'].isin(costos['ITEM'].unique()))]['ULTIMO_CAMBIO'].unique()

array(['2026-05-12', '2026-05-08', '2026-05-10', '2026-05-13',
       '2026-05-09', '2026-05-11'], dtype=object)

In [8]:
uc[(~uc['ORIN'].isin(costos['ITEM'].unique())) & (uc['ULTIMO_CAMBIO']=='2026-05-08')]

,GEOG_LOCL_COD,ORIN,ARTC_ARTC_ID,GEOG_LOCL_ID,ORIGIN_COUNTRY_ID,UNIT_COST,ULTIMO_CAMBIO
1598,111,1000038410,63904,2,UYU,20.50,2026-05-08
1599,322,1000038410,63904,89,UYU,20.50,2026-05-08
1600,309,1000038410,63904,76,UYU,20.50,2026-05-08
1601,160,1000038410,63904,51,UYU,20.50,2026-05-08
1602,158,1000038410,63904,49,UYU,20.50,2026-05-08
...,...,...,...,...,...,...,...
28811,103,1000599481,15824900,22,UYU,52.25,2026-05-08
28812,311,1000599481,15824900,78,UYU,52.25,2026-05-08
28813,318,1000599481,15824900,85,UYU,52.25,2026-05-08
28814,163,1000599481,15824900,140,UYU,52.25,2026-05-08
28815,101,1000599481,15824900,21,UYU,52.25,2026-05-08

In [19]:
costos[costos['STATUS_DESC']=='Impactado']

,ITEM,SUPPLIER,COST_CHANGE,COST_CHANGE_DESC,USER_ID,CREATE_DATETIME,UNIT_COST,STATUS,STATUS_DESC,ACTIVE_DATE,COST_CHANGE_ORIGIN,REASON
0,1.000593e+09,2727.0,4164655,ALIEMNTICIA-NUEV,MEINLLER.BAROSIC,6/5/2026 10:52:07,268.51,E,Impactado,7/5/2026,SKU,5.0
1,1.000438e+09,2727.0,4164655,ALIEMNTICIA-NUEV,MEINLLER.BAROSIC,6/5/2026 10:52:07,85.03,E,Impactado,7/5/2026,SKU,5.0
2,1.000059e+09,2727.0,4164655,ALIEMNTICIA-NUEV,MEINLLER.BAROSIC,6/5/2026 10:52:07,58.38,E,Impactado,7/5/2026,SKU,5.0
3,1.000456e+09,2727.0,4164655,ALIEMNTICIA-NUEV,MEINLLER.BAROSIC,6/5/2026 10:52:07,389.26,E,Impactado,7/5/2026,SKU,5.0
4,1.000438e+09,2727.0,4164655,ALIEMNTICIA-NUEV,MEINLLER.BAROSIC,6/5/2026 10:52:07,85.03,E,Impactado,7/5/2026,SKU,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1178,1.000591e+09,9521.0,4164883,COSTOS OFERTATA MUNDIAL,MARCELA.GALATI,13/5/2026 00:09:17,154.31,E,Impactado,13/5/2026,SKU,10.0
1179,1.000409e+09,1440.0,4164883,COSTOS OFERTATA MUNDIAL,MARCELA.GALATI,13/5/2026 00:09:17,30.56,E,Impactado,13/5/2026,SKU,10.0
1180,1.000588e+09,9521.0,4164883,COSTOS OFERTATA MUNDIAL,MARCELA.GALATI,13/5/2026 00:09:17,28.72,E,Impactado,13/5/2026,SKU,10.0
1181,1.000052e+09,1068.0,4164883,COSTOS OFERTATA MUNDIAL,MARCELA.GALATI,13/5/2026 00:09:17,89.96,E,Impactado,13/5/2026,SKU,10.0
1182,1.000435e+09,1068.0,4164883,COSTOS OFERTATA MUNDIAL,MARCELA.GALATI,13/5/2026 00:09:17,30.01,E,Impactado,13/5/2026,SKU,10.0

In [18]:
costos['STATUS_DESC'].unique()

array(['Impactado', 'Aprobado', 'Otro'], dtype=object)

In [2]:
inflacion_usa = pd.read_excel("Inflacion USA.xlsx")
inflacion_usa

        Mes  Inflacion
0   2024-01        0.3
1   2024-02        0.4
2   2024-03        0.4
3   2024-04        0.3
4   2024-05        0.0
5   2024-06        0.1
6   2024-07        0.2
7   2024-08        0.2
8   2024-09        0.2
9   2024-10        0.2
10  2024-11        0.3
11  2024-12        0.4
12  2025-01        0.5
13  2025-02        0.2
14  2025-03        0.2
15  2025-04        0.2
16  2025-05        0.2
17  2025-06        0.3
18  2025-07        0.2
19  2025-08        0.2
20  2025-09        0.3
21  2025-10        0.2
22  2025-11        0.3
23  2025-12        0.3
24  2026-01        0.2
25  2026-02        0.3
26  2026-03        0.9
27  2026-04        0.6

In [2]:
inflacion = pd.read_excel("Inflación.xlsx")
inflacion

        Mes  Inflacion
0   2024-01       0.51
1   2024-02       0.64
2   2024-03       0.70
3   2024-04       0.36
4   2024-05       0.40
5   2024-06      -0.09
6   2024-07       0.09
7   2024-08       0.42
8   2024-09       0.57
9   2024-10       0.73
10  2024-11       0.48
11  2024-12       0.34
12  2025-01       1.10
13  2025-02       0.69
14  2025-03       0.57
15  2025-04       0.32
16  2025-05       0.11
17  2025-06      -0.09
18  2025-07       0.05
19  2025-08      -0.03
20  2025-09       0.42
21  2025-10       0.40
22  2025-11       0.14
23  2025-12      -0.09
24  2026-01       0.92
25  2026-02       0.35
26  2026-03       0.41
27  2026-04       0.54

In [16]:
import pandas as pd

# ── Rutas de archivos ──────────────────────────────────────────────────────────
CSV_PATH   = r"C:\Users\marcos.larran\Downloads\2026-05-11T14-36_export.csv"
XLSX_PATH  = "Inflación.xlsx"

# ── Carga de datos ─────────────────────────────────────────────────────────────
df = pd.read_csv(CSV_PATH)#.dropna(subset='ULTIMO_CAMBIO')
df

,Unnamed: 0,FECHA_SOLICITUD,SUPPLIER,LISTA,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,VENTA,VENTA_TOTAL_LISTA,PESO_VENTA,...,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,PVP_MARGEN_OBJETIVO,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,ESTADO,COSTO X INFLACION AM,COSTO X INFLACION 2AM
0,73,2026-05-04,2218,25,0,1000042152,ESMALTE COLORAMA PIEL BLANCA 1.00 U,0.00,41092024.71,0.000000,...,81.98,NaN,190.21,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
1,74,2026-05-04,2218,25,0,1000149996,POLVO COMPACTO VOGUE AVELLANA,0.00,41092024.71,0.000000,...,249.69,NaN,624.23,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
2,75,2026-05-04,2218,25,0,1000253952,ESMALTE VOGUE EFECTO GEL VOLUNTAD 14 ML,0.00,41092024.71,0.000000,...,156.79,NaN,235.19,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
3,76,2026-05-04,2218,25,0,1000101799,ACONDICIONADOR ELVIVE 200 ML. SOLAR.,0.00,41092024.71,0.000000,...,57.67,NaN,98.04,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
4,77,2026-05-04,2218,25,0,1000160846,SHAMPOO ELVIVE DREAM LONG LISS 370ML,0.00,41092024.71,0.000000,...,245.06,NaN,593.05,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,1153,2026-05-04,2218,25,0,1000150390,ESMALTE FANTASTIC DESTELLO PARDO 304,0.00,41092024.71,0.000000,...,67.64,NaN,137.32,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
1081,1154,2026-05-04,2218,25,0,1000098663,TINTA NUTRISSE COR INTENSA CASTAÃO OSCURO CEN...,804058.63,41092024.71,0.019567,...,199.26,0.17,384.57,269.0010,NaN,NaN,NaN,NaN,175.254879,185.345157
1082,1155,2026-05-04,2218,25,0,1000098972,TINTA NUTRISSE COLORISSIMOS BORGONIA 4460 BORG...,161412.71,41092024.71,0.003928,...,400.47,0.03,997.18,540.6345,NaN,NaN,NaN,NaN,401.063058,424.154214
1083,1156,2026-05-04,2218,25,0,1000042179,ESMALTE COLORAMA ROSA INCREIVE 1.00 U,0.00,41092024.71,0.000000,...,46.05,NaN,81.06,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
1084,1157,2026-05-04,2218,25,0,1000102104,ACONDICIONADOR ANTI QUIEBRE ELVIVE 200.00 ML,0.00,41092024.71,0.000000,...,52.95,NaN,95.31,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000

In [14]:
df.iloc[:,:20]

,Unnamed: 0,FECHA_SOLICITUD,SUPPLIER,LISTA,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,VENTA,VENTA_TOTAL_LISTA,PESO_VENTA,UNIDADES,GB1,GB2,GB2_AA,COSTO_ACTUAL,ULTIMO_CAMBIO,MG,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO
6,79,2026-05-04,2218,25,0,1000098939,TINTA NUTRISSE RUBIO OSCURO CAPUCCINO 60 45 GR...,117658.74,41092024.71,0.002863,202,39133,39133,155570,388.74,2026-01-31,0.35,436.16,0.12,955.19
13,86,2026-05-04,2218,25,0,1000098897,TINTA EXCELLENCE CREME RUBIO OSCURO 6 RUBIO OS...,74178.22,41092024.71,0.001805,94,20452,20452,470,571.55,2026-01-31,0.35,623.78,0.09,1260.05
23,96,2026-05-04,2218,25,0,1000038855,ACONDICIONADOR ELVIVE COLORVIVE 200 ML,365437.28,41092024.71,0.008893,1094,109507,109507,128256,233.94,2026-04-05,0.29,243.39,0.04,567.10
42,115,2026-05-04,2218,25,0,1000041071,CUBRE CANAS LOREAL CASTAÃO CLARO 57 GR,95230.83,41092024.71,0.002318,114,33577,33577,-424,540.82,2026-01-31,NaN,579.22,0.07,1349.58
44,117,2026-05-04,2218,25,0,1000098669,TINTA GARNIER NUTRISSE INTENSE NÂ° 6.46 ROJO C...,650821.15,41092024.71,0.015838,2283,263010,307762,103044,169.87,2026-03-29,0.35,190.59,0.12,348.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,1111,2026-05-04,2218,25,0,1000098672,TINTA NUTRISSE COR INTENSA RUBIO MUY CLARO 90 ...,790018.79,41092024.71,0.019226,2720,327967,327967,310162,169.87,2026-03-29,0.35,199.26,0.17,370.62
1071,1144,2026-05-04,2218,25,0,1000098660,TINTA NUTRISSE COR INTENSA RUBIO DORADO 73 MIE...,524701.59,41092024.71,0.012769,1875,206197,206197,177584,169.87,2026-03-29,0.35,192.32,0.13,457.74
1075,1148,2026-05-04,2218,25,0,1000038583,SHAMPOO FRUCTIS RECARGA NUTRITIVA 350 ML,469115.93,41092024.71,0.011416,1480,247367,247367,246284,149.83,2026-04-09,0.29,155.88,0.04,318.00
1081,1154,2026-05-04,2218,25,0,1000098663,TINTA NUTRISSE COR INTENSA CASTAÃO OSCURO CEN...,804058.63,41092024.71,0.019567,2866,317215,356090,383317,169.87,2026-03-29,0.35,199.26,0.17,384.57
1082,1155,2026-05-04,2218,25,0,1000098972,TINTA NUTRISSE COLORISSIMOS BORGONIA 4460 BORG...,161412.71,41092024.71,0.003928,262,59561,59561,30624,388.74,2026-01-31,0.35,400.47,0.03,997.18

In [4]:
# ── Preparación de la tabla de inflación ──────────────────────────────────────
# Convertir 'Mes' a período mensual (ej: "2025-04" → Period('2025-04', 'M'))
inflacion["Mes"] = pd.to_datetime(inflacion["Mes"], format="%Y-%m").dt.to_period("M")

# La inflación del excel viene en % sobre 1 (0.54 = 0.54%), convertir a factor multiplicador
# Factor = 1 + (inflacion / 100)
inflacion["factor"] = 1 + inflacion["Inflacion"] / 100
inflacion

        Mes  Inflacion  factor
0   2024-01       0.51  1.0051
1   2024-02       0.64  1.0064
2   2024-03       0.70  1.0070
3   2024-04       0.36  1.0036
4   2024-05       0.40  1.0040
5   2024-06      -0.09  0.9991
6   2024-07       0.09  1.0009
7   2024-08       0.42  1.0042
8   2024-09       0.57  1.0057
9   2024-10       0.73  1.0073
10  2024-11       0.48  1.0048
11  2024-12       0.34  1.0034
12  2025-01       1.10  1.0110
13  2025-02       0.69  1.0069
14  2025-03       0.57  1.0057
15  2025-04       0.32  1.0032
16  2025-05       0.11  1.0011
17  2025-06      -0.09  0.9991
18  2025-07       0.05  1.0005
19  2025-08      -0.03  0.9997
20  2025-09       0.42  1.0042
21  2025-10       0.40  1.0040
22  2025-11       0.14  1.0014
23  2025-12      -0.09  0.9991
24  2026-01       0.92  1.0092
25  2026-02       0.35  1.0035
26  2026-03       0.41  1.0041
27  2026-04       0.54  1.0054

In [ ]:
# Último período disponible en la tabla de inflación
ultimo_periodo = inflacion["Mes"].max()
print(f"Último período de inflación: {ultimo_periodo}")

Último período de inflación: 2026-04

In [ ]:
# ── Función para calcular el factor acumulado por fila ────────────────────────
def calcular_factor_acumulado(fecha_ultimo_cambio: str) -> float:
    """
    Dado el ULTIMO_CAMBIO de un artículo, calcula el factor de inflación
    acumulado desde el mes SIGUIENTE al del último cambio hasta el último
    período disponible en la tabla de inflación (inclusive).
    """
    try:
        periodo_cambio = pd.to_datetime(fecha_ultimo_cambio).to_period("M")
        periodo_inicio = periodo_cambio + 1  # mes siguiente al cambio

        mascara = (inflacion["Mes"] >= periodo_inicio) & (inflacion["Mes"] <= ultimo_periodo)
        factores = inflacion.loc[mascara, "factor"]

        if factores.empty:
            return 1.0  # sin inflación aplicable

        return factores.prod()
    except:
        return 1.0

In [19]:
# ── Aplicar cálculo al dataframe ──────────────────────────────────────────────
df["factor_inflacion"] = df["ULTIMO_CAMBIO"].apply(calcular_factor_acumulado)
df

,Unnamed: 0,FECHA_SOLICITUD,SUPPLIER,LISTA,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,VENTA,VENTA_TOTAL_LISTA,PESO_VENTA,...,INCREMENTO,PVP_SUGERIDO,PVP_MARGEN_OBJETIVO,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,ESTADO,COSTO X INFLACION AM,COSTO X INFLACION 2AM,factor_inflacion
0,73,2026-05-04,2218,25,0,1000042152,ESMALTE COLORAMA PIEL BLANCA 1.00 U,0.00,41092024.71,0.000000,...,NaN,190.21,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1,74,2026-05-04,2218,25,0,1000149996,POLVO COMPACTO VOGUE AVELLANA,0.00,41092024.71,0.000000,...,NaN,624.23,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
2,75,2026-05-04,2218,25,0,1000253952,ESMALTE VOGUE EFECTO GEL VOLUNTAD 14 ML,0.00,41092024.71,0.000000,...,NaN,235.19,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
3,76,2026-05-04,2218,25,0,1000101799,ACONDICIONADOR ELVIVE 200 ML. SOLAR.,0.00,41092024.71,0.000000,...,NaN,98.04,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
4,77,2026-05-04,2218,25,0,1000160846,SHAMPOO ELVIVE DREAM LONG LISS 370ML,0.00,41092024.71,0.000000,...,NaN,593.05,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,1153,2026-05-04,2218,25,0,1000150390,ESMALTE FANTASTIC DESTELLO PARDO 304,0.00,41092024.71,0.000000,...,NaN,137.32,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1081,1154,2026-05-04,2218,25,0,1000098663,TINTA NUTRISSE COR INTENSA CASTAÃO OSCURO CEN...,804058.63,41092024.71,0.019567,...,0.17,384.57,269.0010,NaN,NaN,NaN,NaN,175.254879,185.345157,1.005400
1082,1155,2026-05-04,2218,25,0,1000098972,TINTA NUTRISSE COLORISSIMOS BORGONIA 4460 BORG...,161412.71,41092024.71,0.003928,...,0.03,997.18,540.6345,NaN,NaN,NaN,NaN,401.063058,424.154214,1.013055
1083,1156,2026-05-04,2218,25,0,1000042179,ESMALTE COLORAMA ROSA INCREIVE 1.00 U,0.00,41092024.71,0.000000,...,NaN,81.06,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1084,1157,2026-05-04,2218,25,0,1000102104,ACONDICIONADOR ANTI QUIEBRE ELVIVE 200.00 ML,0.00,41092024.71,0.000000,...,NaN,95.31,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000

In [20]:
df.iloc[:,10:]

,UNIDADES,GB1,GB2,GB2_AA,COSTO_ACTUAL,ULTIMO_CAMBIO,MG,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,PVP_MARGEN_OBJETIVO,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,ESTADO,COSTO X INFLACION AM,COSTO X INFLACION 2AM,factor_inflacion
0,0,0,0,0,0.00,NaN,NaN,81.98,NaN,190.21,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1,0,0,0,0,0.00,NaN,NaN,249.69,NaN,624.23,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
2,0,0,0,0,0.00,NaN,NaN,156.79,NaN,235.19,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
3,0,0,0,0,0.00,NaN,NaN,57.67,NaN,98.04,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
4,0,0,0,18889,0.00,NaN,NaN,245.06,NaN,593.05,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1080,0,0,0,0,0.00,NaN,NaN,67.64,NaN,137.32,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1081,2866,317215,356090,383317,169.87,2026-03-29,0.35,199.26,0.17,384.57,269.0010,NaN,NaN,NaN,NaN,175.254879,185.345157,1.005400
1082,262,59561,59561,30624,388.74,2026-01-31,0.35,400.47,0.03,997.18,540.6345,NaN,NaN,NaN,NaN,401.063058,424.154214,1.013055
1083,0,0,0,0,0.00,NaN,NaN,46.05,NaN,81.06,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000
1084,0,0,0,0,0.00,NaN,NaN,52.95,NaN,95.31,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000

In [ ]:
df["costo por inflacion"] = df["COSTO_ACTUAL"] * df["factor_inflacion"]

# Redondear a 2 decimales
df["costo por inflacion"] = df["costo por inflacion"].round(2)

# Eliminar columna auxiliar si no se quiere en el output
df = df.drop(columns=["factor_inflacion"])
df

,Unnamed: 0,FECHA_SOLICITUD,SUPPLIER,LISTA,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,VENTA,VENTA_TOTAL_LISTA,PESO_VENTA,...,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,PVP_MARGEN_OBJETIVO,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,ESTADO,SUGERENCIA,costo por inflacion
0,0,2026-03-03,1195,3,101,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,2213813.76,2213813.76,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
1,1,2026-03-03,1195,3,102,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,333169.32,333169.32,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
2,2,2026-03-03,1195,3,103,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,3462726.00,3462726.00,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
3,3,2026-03-03,1195,3,104,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,1513029.84,1513029.84,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
4,4,2026-03-03,1195,3,108,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,421999.08,421999.08,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
5,5,2026-03-03,1195,3,115,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,23715070.32,23715070.32,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5
6,6,2026-03-03,1195,3,120,1000049599,AGUA MINERAL SALUS SIN GAS 600 ML,225709.80,225709.80,1,...,40,0.02,60,46.4,NaN,NaN,NaN,NaN,Aprobar,40.5

In [ ]:

# ── Guardar resultado ──────────────────────────────────────────────────────────
df.to_csv(OUTPUT_PATH, index=False)
print(f"Archivo guardado en: {OUTPUT_PATH}")

# ── Vista previa ───────────────────────────────────────────────────────────────
print("\nVista previa:")
print(df[["ARTC_ARTC_DESC", "COSTO_ACTUAL", "ULTIMO_CAMBIO", "costo por inflacion"]].head(10).to_string())

In [19]:
'2026-01'.find('.')

-1

In [15]:
inflacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Mes        28 non-null     object
 1   Inflacion  28 non-null     float64
dtypes: float64(1), object(1)
memory usage: 580.0+ bytes

In [22]:
max(inflacion['Mes']).split('-')[1]

'04'

In [23]:
'0,4'.replace(',', '.')

'0.4'

In [21]:
int(max(inflacion['Mes']).split('-')[1])

4

In [24]:
def inflacion_movil(series, ventana):
    tasas = series.iloc[-ventana:]
    acum = 1.0
    for t in tasas:
        acum *= (1 + t / 100)
    return round((acum - 1) * 100, 4)

In [39]:
inf_12 = round(inflacion_movil(inflacion["Inflacion"], 12)/100, 4)
inf_24 = round(inflacion_movil(inflacion["Inflacion"], 24)/100, 4)
inf_12

0.0316

In [27]:
per_nuevo = '2026-05'
inf_nueva = 0.1

In [32]:
inflacion.loc[len(inflacion)] = (per_nuevo, inf_nueva)
inflacion

        Mes  Inflacion
0   2024-01       0.51
1   2024-02       0.64
2   2024-03       0.70
3   2024-04       0.36
4   2024-05       0.40
5   2024-06      -0.09
6   2024-07       0.09
7   2024-08       0.42
8   2024-09       0.57
9   2024-10       0.73
10  2024-11       0.48
11  2024-12       0.34
12  2025-01       1.10
13  2025-02       0.69
14  2025-03       0.57
15  2025-04       0.32
16  2025-05       0.11
17  2025-06      -0.09
18  2025-07       0.05
19  2025-08      -0.03
20  2025-09       0.42
21  2025-10       0.40
22  2025-11       0.14
23  2025-12      -0.09
24  2026-01       0.92
25  2026-02       0.35
26  2026-03       0.41
27  2026-04       0.54
28  2026-05       0.10

In [33]:
inflacion.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Mes        29 non-null     object
 1   Inflacion  29 non-null     float64
dtypes: float64(1), object(1)
memory usage: 696.0+ bytes

In [3]:
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from google.oauth2.service_account import Credentials
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from gspread.exceptions import APIError, WorksheetNotFound

In [6]:
credentials_drive = get_credentials("credentials_mail_servicio")

In [29]:
scopes = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

#credentials = Credentials.from_service_account_file('C:\\Users\\leonardo.mangold\\PycharmProjects\\promos_inteligencia_negocio\\ft_promos_automatico\\leo_usuario_servicio_credenciales.json', scopes=scopes)
credentials = Credentials.from_service_account_info(credentials_drive, scopes=scopes)

gc = gspread.authorize(credentials)

gauth = GoogleAuth()
drive = GoogleDrive(gauth)

In [30]:
gs = gc.open_by_key('19k___10iUJ_k4utQvE8qCdF9LuDAvfDkBLIF6dh8HOM')

In [32]:
ws = gs.worksheet('DETALLE x Acuerdo')
data = pd.DataFrame(ws.get_all_values())
data

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,,Dept (Sector),Group,Codigo,Nombre Proveedor,Entradas $,Ret. Grales,Eventos Comerciales,No devoluc,Centralizac.,...,Escala 3,Escala 4,Escala 5,Periodo de las Escala,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,No renovados,Nº Acuerdo,Fecha de Vencimiento RMS,Plazo pago
1,COMESTIBLES1014,ALTA ROTACION - ALMACEN,COMESTIBLES,1014,Antil S.A,8.988.195,,,,,...,,,,,,,,,,
2,COMESTIBLES1024,ALTA ROTACION - ALMACEN,COMESTIBLES,1024,ANCAL S.A.,5.707.400,,,,,...,,,,,,,,,,
3,COMESTIBLES1041,ALTA ROTACION - ALMACEN,COMESTIBLES,1041,ALGORTA S.A.,13.572.017,,,,,...,,,,,,,,,,
4,COMESTIBLES1212,ALTA ROTACION - ALMACEN,COMESTIBLES,1212,ALMENA S.A.,1.141.589,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,BEBIDAS61986,BEBIDAS,BEBIDAS,61986,ROSES HERMANOS S R L,10.310.783,,,,,...,,,,,,,,,,
705,BEBIDAS62414,BEBIDAS,BEBIDAS,62414,CABORIL SOCIEDAD ANONIMA,4.313.891,,,,,...,,,,,,,,,,
706,BEBIDAS62420,BEBIDAS,BEBIDAS,62420,VALDI FRAGA FERNANDO JORGE,31.320,,,,,...,,,,,,,,,,
707,,BEBIDAS,BEBIDAS,,BLODWEN SA,0,"11,90%","3,00%","2,00%","6,00%",...,15% - 2%,,,Trimestral,01/10/2025,31/03/2027,,6825123,31/12/2027,75 dias
708,BEBIDAS62786,BEBIDAS,BEBIDAS,62786,GHELFA GUSTAVO Y GHELFA GONZALO,142.049,,,,,...,,,,,,,,,,

In [77]:
contratos = data.iloc[1:,:].replace('', pd.NA)
contratos.columns = data.iloc[0,:]
contratos

,,Dept (Sector),Group,Codigo,Nombre Proveedor,Entradas $,Ret. Grales,Eventos Comerciales,No devoluc,Centralizac.,...,Escala 3,Escala 4,Escala 5,Periodo de las Escala,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,No renovados,Nº Acuerdo,Fecha de Vencimiento RMS,Plazo pago
1,COMESTIBLES1014,ALTA ROTACION - ALMACEN,COMESTIBLES,1014,Antil S.A,8.988.195,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,COMESTIBLES1024,ALTA ROTACION - ALMACEN,COMESTIBLES,1024,ANCAL S.A.,5.707.400,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,COMESTIBLES1041,ALTA ROTACION - ALMACEN,COMESTIBLES,1041,ALGORTA S.A.,13.572.017,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,COMESTIBLES1212,ALTA ROTACION - ALMACEN,COMESTIBLES,1212,ALMENA S.A.,1.141.589,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5,COMESTIBLES1326,ALTA ROTACION - ALMACEN,COMESTIBLES,1326,ANTILUR S.A.,15.422.883,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,BEBIDAS61986,BEBIDAS,BEBIDAS,61986,ROSES HERMANOS S R L,10.310.783,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
705,BEBIDAS62414,BEBIDAS,BEBIDAS,62414,CABORIL SOCIEDAD ANONIMA,4.313.891,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
706,BEBIDAS62420,BEBIDAS,BEBIDAS,62420,VALDI FRAGA FERNANDO JORGE,31.320,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
707,<NA>,BEBIDAS,BEBIDAS,<NA>,BLODWEN SA,0,"11,90%","3,00%","2,00%","6,00%",...,15% - 2%,<NA>,<NA>,Trimestral,01/10/2025,31/03/2027,<NA>,6825123,31/12/2027,75 dias
708,BEBIDAS62786,BEBIDAS,BEBIDAS,62786,GHELFA GUSTAVO Y GHELFA GONZALO,142.049,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [78]:
contratos = contratos[['Codigo', 'Nombre Proveedor', 'Fecha Acuerdo Desde', 'Fecha Acuerdo Hasta',
                       'Fecha de Vencimiento RMS']].dropna().drop_duplicates()
contratos

,Codigo,Nombre Proveedor,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS
22,3196,COOPAR S.A.,01/03/2026,28/02/2027,31/12/2027
26,4004,DURULTE S.A.,01/01/2026,31/12/2026,31/03/2027
28,4035,DISTRIBUIDORA SAN JOSE S.A.,01/01/2026,31/12/2026,31/12/2027
31,4315,DEL GAUCHO S.R.L.,01/01/2026,31/12/2026,31/12/2027
36,6037,FERAL S.A,01/01/2026,31/12/2026,31/12/2027
...,...,...,...,...,...
623,61337,MEGSOLUTION SRL,01/04/2026,01/04/2027,30/06/2027
625,62475,MUZGA SA,01/04/2026,01/04/2027,30/06/2027
626,2108901,AIWA URUGUAY SAS,25/11/2025,31/11/2026,31/12/2027
630,2144,CEPAS URUGUAY SA,01/01/2025,31/12/2026,31/12/2026
685,1636,AGROLAND S A,01/01/2026,30/06/2027,31/12/2027

In [79]:
contratos['CONTRATOS_DESDE'] = pd.to_datetime(contratos['Fecha Acuerdo Desde'], dayfirst=True, errors='coerce')
contratos['CONTRATOS_HASTA'] = pd.to_datetime(contratos['Fecha Acuerdo Hasta'], dayfirst=True, errors='coerce')
contratos['CONTRATOS_VENCIMIENTO'] = pd.to_datetime(contratos['Fecha de Vencimiento RMS'], dayfirst=True, errors='coerce')
contratos

,Codigo,Nombre Proveedor,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO
22,3196,COOPAR S.A.,01/03/2026,28/02/2027,31/12/2027,2026-03-01,2027-02-28,2027-12-31
26,4004,DURULTE S.A.,01/01/2026,31/12/2026,31/03/2027,2026-01-01,2026-12-31,2027-03-31
28,4035,DISTRIBUIDORA SAN JOSE S.A.,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
31,4315,DEL GAUCHO S.R.L.,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
36,6037,FERAL S.A,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
...,...,...,...,...,...,...,...,...
623,61337,MEGSOLUTION SRL,01/04/2026,01/04/2027,30/06/2027,2026-04-01,2027-04-01,2027-06-30
625,62475,MUZGA SA,01/04/2026,01/04/2027,30/06/2027,2026-04-01,2027-04-01,2027-06-30
626,2108901,AIWA URUGUAY SAS,25/11/2025,31/11/2026,31/12/2027,2025-11-25,NaT,2027-12-31
630,2144,CEPAS URUGUAY SA,01/01/2025,31/12/2026,31/12/2026,2025-01-01,2026-12-31,2026-12-31
685,1636,AGROLAND S A,01/01/2026,30/06/2027,31/12/2027,2026-01-01,2027-06-30,2027-12-31

In [80]:
contratos['Codigo'] = contratos['Codigo'].astype('int64')
contratos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 155 entries, 22 to 685
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Codigo                    155 non-null    int64
 1   Nombre Proveedor          155 non-null    object
 2   Fecha Acuerdo Desde       155 non-null    object
 3   Fecha Acuerdo Hasta       155 non-null    object
 4   Fecha de Vencimiento RMS  155 non-null    object
 5   CONTRATOS_DESDE           154 non-null    datetime64[ns]
 6   CONTRATOS_HASTA           148 non-null    datetime64[ns]
 7   CONTRATOS_VENCIMIENTO     154 non-null    datetime64[ns]
dtypes: datetime64[ns](3), int64(1), object(4)
memory usage: 10.9+ KB

In [50]:
#Conectamos a snowflake
credentials_snowflake = get_credentials("snow")
user, cursor, snow = snowflake_login(
                                    user = credentials_snowflake['USER'],
                                    password = credentials_snowflake['PASS'],
                                    account = credentials_snowflake['ACCOUNT']
                                    )

Intento 1

2026-05-05 17:05:53.986
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\marcos.larran\AppData\Local\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

Correct Password - connected to SNOWFLAKE

In [51]:
cursor.execute('SELECT * FROM MSTRDB.DWH.SUPS;')
sup = cursor.fetch_pandas_all()
sup

,SUPPLIER,SUP_NAME,SUP_NAME_SECONDARY,SUPPLIER_PARENT,CONTACT_NAME,CONTACT_PHONE,CONTACT_FAX,CONTACT_PAGER,SUP_STATUS,QC_IND,...,BRACKET_COSTING_IND,VMI_ORDER_STATUS,DSD_IND,SCALE_AIP_ORDERS,FINAL_DEST_IND,SUP_QTY_LEVEL,EXTERNAL_REF_ID,CREATE_ID,CREATE_DATETIME,STATUS_UPD_BY_RMS
0,8534,BOX SRL,213902550017,NaN,***NoTiene*** X,9999999,02668,None,I,N,...,N,None,N,N,N,EA,2667,RMS_MIG,2019-04-07,N
1,15160,ESTAWOL S.A. - CENTRAL - USD,218454570010,15159.0,AGUSTINA MIERES,2 91501030,60150,None,A,N,...,N,None,Y,N,N,EA,CENTRAL,RMS,2019-09-24,None
2,15159,ESTAWOL S.A.,218454570010,NaN,AGUSTINA MIERES,91501030,60150,None,A,N,...,N,None,N,N,N,EA,7262,RMS,2019-09-24,None
3,14681,QINGDAO ZHICHENGTIANYI TRADING CO.LT - CENTRAL...,19025,14680.0,***NoTiene*** X,2 053268078147,19025,None,A,N,...,N,None,Y,N,N,EA,CENTRAL,RMS,2019-07-31,None
4,14680,QINGDAO ZHICHENGTIANYI TRADING CO.LT,19025,NaN,***NoTiene*** X,053268078147,19025,None,A,N,...,N,None,N,N,N,EA,5993,RMS,2019-07-31,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6023,4434,MARCELO ZAPARRART CARDOZO,214592480014,NaN,MARCELO ZAPARRART,9999999,14453,None,I,N,...,N,None,N,N,N,EA,5126,RMS_MIG,2019-04-07,N
6024,4431,NICDO SRL - CENTRAL - UYU,216016980017,4430.0,NICOLE ERENBERG,598 2 29000202,15151,None,A,N,...,N,None,Y,N,N,EA,CENTRAL,RMS_MIG,2019-04-07,N
6025,4430,NICDO SRL,216016980017,NaN,NICOLE ERENBERG,598 :29000202,15151,None,A,N,...,N,None,N,N,N,EA,5537,RMS_MIG,2019-04-07,N
6026,3948,DANTYZUL S.A.,215151250015,NaN,***NoTiene*** X,9999999,04350,None,I,N,...,N,None,N,N,N,EA,3191,RMS_MIG,2019-04-07,N
6027,7843,JEFATURA DE POLICIA DE ROCHA - SITIO CENTRAL -...,10208,7842.0,NO DATA NO DATA,0000 0000,10208,None,A,N,...,N,None,N,N,N,EA,None,RMS_MIG,2019-04-07,N

In [52]:
sup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6028 entries, 0 to 6027
Data columns (total 69 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   SUPPLIER                6028 non-null   int32
 1   SUP_NAME                6028 non-null   object
 2   SUP_NAME_SECONDARY      5952 non-null   object
 3   SUPPLIER_PARENT         3102 non-null   float64
 4   CONTACT_NAME            6028 non-null   object
 5   CONTACT_PHONE           6028 non-null   object
 6   CONTACT_FAX             6027 non-null   object
 7   CONTACT_PAGER           151 non-null    object
 8   SUP_STATUS              6028 non-null   object
 9   QC_IND                  6028 non-null   object
 10  QC_PCT                  0 non-null      float64
 11  QC_FREQ                 0 non-null      float64
 12  VC_IND                  6028 non-null   object
 13  VC_PCT                  0 non-null      float64
 14  VC_FREQ                 0 non-null      float64
 15  CURRENCY_CODE           6028 non-null   object
 16  LANG                    806 non-null    float64
 17  TERMS                   6028 non-null   object
 18  FREIGHT_TERMS           6028 non-null   object
 19  RET_ALLOW_IND           6028 non-null   object
 20  RET_AUTH_REQ            6028 non-null   object
 21  RET_MIN_DOL_AMT         0 non-null      float64
 22  RET_COURIER             0 non-null      object
 23  HANDLING_PCT            0 non-null      float64
 24  EDI_PO_IND              6028 non-null   object
 25  EDI_PO_CHG              6028 non-null   object
 26  EDI_PO_CONFIRM          6028 non-null   object
 27  EDI_ASN                 6028 non-null   object
 28  EDI_SALES_RPT_FREQ      0 non-null      object
 29  EDI_SUPP_AVAILABLE_IND  6028 non-null   object
 30  EDI_CONTRACT_IND        6028 non-null   object
 31  EDI_INVC_IND            6028 non-null   object
 32  EDI_CHANNEL_ID          0 non-null      float64
 33  COST_CHG_PCT_VAR        0 non-null      float64
 34  COST_CHG_AMT_VAR        0 non-null      float64
 35  REPLEN_APPROVAL_IND     6028 non-null   object
 36  SHIP_METHOD             1 non-null      object
 37  PAYMENT_METHOD          4917 non-null   object
 38  CONTACT_TELEX           3 non-null      object
 39  CONTACT_EMAIL           5958 non-null   object
 40  SETTLEMENT_CODE         6028 non-null   object
 41  PRE_MARK_IND            6028 non-null   object
 42  AUTO_APPR_INVC_IND      6028 non-null   object
 43  DBT_MEMO_CODE           6028 non-null   object
 44  FREIGHT_CHARGE_IND      6028 non-null   object
 45  AUTO_APPR_DBT_MEMO_IND  6028 non-null   object
 46  PREPAY_INVC_IND         6028 non-null   object
 47  BACKORDER_IND           6028 non-null   object
 48  VAT_REGION              6028 non-null   int16
 49  INV_MGMT_LVL            6028 non-null   object
 50  SERVICE_PERF_REQ_IND    6028 non-null   object
 51  INVC_PAY_LOC            4882 non-null   object
 52  INVC_RECEIVE_LOC        4882 non-null   object
 53  ADDINVC_GROSS_NET       4934 non-null   object
 54  DELIVERY_POLICY         6028 non-null   object
 55  COMMENT_DESC            2 non-null      object
 56  DEFAULT_ITEM_LEAD_TIME  0 non-null      float64
 57  DUNS_NUMBER             0 non-null      object
 58  DUNS_LOC                0 non-null      object
 59  BRACKET_COSTING_IND     6028 non-null   object
 60  VMI_ORDER_STATUS        0 non-null      object
 61  DSD_IND                 6028 non-null   object
 62  SCALE_AIP_ORDERS        6028 non-null   object
 63  FINAL_DEST_IND          6028 non-null   object
 64  SUP_QTY_LEVEL           6028 non-null   object
 65  EXTERNAL_REF_ID         5444 non-null   object
 66  CREATE_ID               6028 non-null   object
 67  CREATE_DATETIME         6028 non-null   object
 68  STATUS_UPD_BY_RMS       4569 non-null   object
dtypes: float64(12), int16(1), int32(1), object(55)
memory usage: 3.1+ MB

In [ ]:
print(contratos.shape)
print(contratos[contratos['Codigo'].isin(sup['SUPPLIER'].unique())].shape)
contratos[contratos['Codigo'].isin(sup['SUPPLIER'].unique())]

(151, 7)
(43, 7)

,Codigo,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO
22,3196,01/03/2026,28/02/2027,31/12/2027,2026-03-01,2027-02-28,2027-12-31
28,4035,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
31,4315,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
36,6037,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31
151,1417,10/03/2026,30/06/2027,31/12/2027,2026-03-10,2027-06-30,2027-12-31
159,6098,10/03/2026,31/12/2027,31/03/2028,2026-03-10,2027-12-31,2028-03-31
174,1551,12/03/2026,31/12/2027,31/03/2028,2026-03-12,2027-12-31,2028-03-31
177,12538,10/03/2026,31/12/2027,31/03/2028,2026-03-10,2027-12-31,2028-03-31
185,1360,01/09/2025,31/07/2026,31/12/2026,2025-09-01,2026-07-31,2026-12-31
187,2001,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31
189,2312,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31
190,3001,01/09/2025,31/07/2026,31/12/2027,2025-09-01,2026-07-31,2027-12-31
194,3132,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31
195,6037,01/09/2025,31/07/2026,31/12/2027,2025-09-01,2026-07-31,2027-12-31
218,1608,01/08/2025,31/07/2027,31/12/2027,2025-08-01,2027-07-31,2027-12-31
219,4490,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31
227,7638,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31
240,3132,17/11/2025,17/11/2026,31/12/2027,2025-11-17,2026-11-17,2027-12-31
243,5013,04/11/2025,04/11/2026,31/12/2027,2025-11-04,2026-11-04,2027-12-31
259,3596,03/07/2025,31/07/2026,31/12/2026,2025-07-03,2026-07-31,2026-12-31
278,7638,14/08/2025,14/08/2026,31/12/2027,2025-08-14,2026-08-14,2027-12-31
282,2312,08/01/2025,31/07/2026,31/12/2027,2025-01-08,2026-07-31,2027-12-31
331,7172,01/07/2025,30/06/2026,31/12/2027,2025-07-01,2026-06-30,2027-12-31
341,1565,01/02/2025,31/12/2025,31/12/2026,2025-02-01,2025-12-31,2026-12-31
353,1333,01/07/2025,31/12/2026,31/12/2027,2025-07-01,2026-12-31,2027-12-31
356,3330,01/09/2025,31/08/2026,31/12/2027,2025-09-01,2026-08-31,2027-12-31
365,7301,01/06/2025,31/06/2026,31/12/2026,2025-06-01,NaT,2026-12-31
366,7301,01/07/2025,30/06/2026,31/12/2026,2025-07-01,2026-06-30,2026-12-31
397,1294,01/12/2025,31/03/2027,31/12/2027,2025-12-01,2027-03-31,2027-12-31
399,3367,01/01/2025,31/12/2025,31/12/2026,2025-01-01,2025-12-31,2026-12-31
402,7108,01/08/2025,30/06/2026,31/12/2027,2025-08-01,2026-06-30,2027-12-31
407,14300,01/10/2025,31/03/2027,31/12/2027,2025-10-01,2027-03-31,2027-12-31
420,1779,01/10/2025,31/03/2027,31/03/2027,2025-10-01,2027-03-31,2027-03-31
440,3027,01/07/2025,30/06/2026,31/12/2027,2025-07-01,2026-06-30,2027-12-31
443,6162,01/07/2025,30/06/2026,31/12/2026,2025-07-01,2026-06-30,2026-12-31
470,1779,01/10/2025,31/03/2027,31/12/2027,2025-10-01,2027-03-31,2027-12-31
471,3992,01/01/2025,30/06/2026,31/12/2027,2025-01-01,2026-06-30,2027-12-31
520,2033901,01/06/2025,31/05/2026,31/12/2026,2025-06-01,2026-05-31,2026-12-31
545,1757,01/06/2025,31/07/2026,31/12/2027,2025-06-01,2026-07-31,2027-12-31
614,2450,01/01/2026,31/12/2027,31/12/2027,2026-01-01,2027-12-31,2027-12-31
626,2108901,25/11/2025,31/11/2026,31/12/2027,2025-11-25,NaT,2027-12-31
630,2144,01/01/2025,31/12/2026,31/12/2026,2025-01-01,2026-12-31,2026-12-31
685,1636,01/01/2026,30/06/2027,31/12/2027,2026-01-01,2027-06-30,2027-12-31

In [61]:
contratos[~contratos['Codigo'].isin(sup['SUPPLIER'].unique())]['Codigo'].unique()

array([ 4004, 14092, 14338, 17004, 18127, 62765, 62677,  4313, 10010,
       11010, 12255, 14143, 15132, 18111, 21058, 21220, 22177, 23001,
        9241, 62879, 62051, 62689,  2097, 14291, 19005, 21071, 21372,
       61890, 62358, 14325, 18382, 62901,  4213, 15151,  9302, 61750,
       62227, 62287, 62463, 61604, 62640,  3237,  5121,  6136,  7166,
        6154, 19002, 21281, 21416,  4420, 14613,  8052, 12129, 12247,
       22049, 22256, 14727,  9279,  9316, 60419, 60730, 61072, 61574,
       61579, 62038, 62057, 62704, 18322, 62841, 18058, 21398, 18441,
       24236, 60413, 60827, 60836, 21233, 21422, 15188, 62857, 61099,
       61688, 62668, 12130, 62756, 18405, 18529, 62499, 62636, 60399,
       62807, 62856, 62882,  6079, 15168, 18262,  4825, 15657, 15235,
       60106, 60879, 61337, 62475], dtype=int64)

In [81]:
for i in sup['CONTACT_FAX'].unique():
    try:
        if len(i) != 5:
            print(i)
    except:
        print(i)

None

In [69]:
def codContFax (c):
    if len(str(c)) == 4:
        return '0' + str(c)
    else:
        return str(c)

In [82]:
contratos['CONTACT_FAX'] = contratos['Codigo'].apply(codContFax)
contratos

,Codigo,Nombre Proveedor,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,CONTACT_FAX
22,3196,COOPAR S.A.,01/03/2026,28/02/2027,31/12/2027,2026-03-01,2027-02-28,2027-12-31,03196
26,4004,DURULTE S.A.,01/01/2026,31/12/2026,31/03/2027,2026-01-01,2026-12-31,2027-03-31,04004
28,4035,DISTRIBUIDORA SAN JOSE S.A.,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31,04035
31,4315,DEL GAUCHO S.R.L.,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31,04315
36,6037,FERAL S.A,01/01/2026,31/12/2026,31/12/2027,2026-01-01,2026-12-31,2027-12-31,06037
...,...,...,...,...,...,...,...,...,...
623,61337,MEGSOLUTION SRL,01/04/2026,01/04/2027,30/06/2027,2026-04-01,2027-04-01,2027-06-30,61337
625,62475,MUZGA SA,01/04/2026,01/04/2027,30/06/2027,2026-04-01,2027-04-01,2027-06-30,62475
626,2108901,AIWA URUGUAY SAS,25/11/2025,31/11/2026,31/12/2027,2025-11-25,NaT,2027-12-31,2108901
630,2144,CEPAS URUGUAY SA,01/01/2025,31/12/2026,31/12/2026,2025-01-01,2026-12-31,2026-12-31,02144
685,1636,AGROLAND S A,01/01/2026,30/06/2027,31/12/2027,2026-01-01,2027-06-30,2027-12-31,01636

In [83]:
contratos_2 = contratos.merge(sup[['SUPPLIER', 'SUP_NAME', 'CONTACT_FAX']], how='left')
contratos_2[contratos_2['SUPPLIER'].isna()]

,Codigo,Nombre Proveedor,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,CONTACT_FAX,SUPPLIER,SUP_NAME
106,7638,LUCIERNAGA AZUL S.A,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31,07638,NaN,NaN
136,7638,LUCIERNAGA AZUL S.A,14/08/2025,14/08/2026,31/12/2027,2025-08-14,2026-08-14,2027-12-31,07638,NaN,NaN
270,2033901,LATIN SPIRIT E y P SRL,01/06/2025,31/05/2026,31/12/2026,2025-06-01,2026-05-31,2026-12-31,2033901,NaN,NaN
323,2108901,AIWA URUGUAY SAS,25/11/2025,31/11/2026,31/12/2027,2025-11-25,NaT,2027-12-31,2108901,NaN,NaN

In [84]:
contratos_2.loc[contratos_2[contratos_2['SUPPLIER'].isna()].index,
                'SUPPLIER'] = contratos_2.loc[contratos_2[contratos_2['SUPPLIER'].isna()].index, 'Codigo']
contratos_2[contratos_2['SUP_NAME'].isna()]

,Codigo,Nombre Proveedor,Fecha Acuerdo Desde,Fecha Acuerdo Hasta,Fecha de Vencimiento RMS,CONTRATOS_DESDE,CONTRATOS_HASTA,CONTRATOS_VENCIMIENTO,CONTACT_FAX,SUPPLIER,SUP_NAME
106,7638,LUCIERNAGA AZUL S.A,01/08/2025,31/07/2026,31/12/2027,2025-08-01,2026-07-31,2027-12-31,07638,7638.0,NaN
136,7638,LUCIERNAGA AZUL S.A,14/08/2025,14/08/2026,31/12/2027,2025-08-14,2026-08-14,2027-12-31,07638,7638.0,NaN
270,2033901,LATIN SPIRIT E y P SRL,01/06/2025,31/05/2026,31/12/2026,2025-06-01,2026-05-31,2026-12-31,2033901,2033901.0,NaN
323,2108901,AIWA URUGUAY SAS,25/11/2025,31/11/2026,31/12/2027,2025-11-25,NaT,2027-12-31,2108901,2108901.0,NaN

In [85]:
contratos_2.columns

Index(['Codigo', 'Nombre Proveedor', 'Fecha Acuerdo Desde',
       'Fecha Acuerdo Hasta', 'Fecha de Vencimiento RMS', 'CONTRATOS_DESDE',
       'CONTRATOS_HASTA', 'CONTRATOS_VENCIMIENTO', 'CONTACT_FAX', 'SUPPLIER',
       'SUP_NAME'],
      dtype='object')

In [88]:
contratos_cargar = contratos_2[['SUPPLIER', 'CONTRATOS_DESDE', 'CONTRATOS_HASTA', 'CONTRATOS_VENCIMIENTO'
                                ]].dropna(subset='SUPPLIER').drop_duplicates().astype({'SUPPLIER':'int64'})
contratos_cargar

     SUPPLIER CONTRATOS_DESDE CONTRATOS_HASTA CONTRATOS_VENCIMIENTO
0        1174      2026-03-01      2027-02-28            2027-12-31
1        1173      2026-03-01      2027-02-28            2027-12-31
2        1286      2026-01-01      2026-12-31            2027-03-31
3        1285      2026-01-01      2026-12-31            2027-03-31
4        1036      2026-01-01      2026-12-31            2027-12-31
..        ...             ...             ...                   ...
323   2108901      2025-11-25             NaT            2027-12-31
324      1138      2025-01-01      2026-12-31            2026-12-31
325      1137      2025-01-01      2026-12-31            2026-12-31
326      7539      2026-01-01      2027-06-30            2027-12-31
327      7538      2026-01-01      2027-06-30            2027-12-31

[318 rows x 4 columns]

In [91]:
contratos_cargar.info()

<class 'pandas.core.frame.DataFrame'>
Index: 318 entries, 0 to 327
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUPPLIER               318 non-null    int64
 1   CONTRATOS_DESDE        316 non-null    datetime64[ns]
 2   CONTRATOS_HASTA        307 non-null    datetime64[ns]
 3   CONTRATOS_VENCIMIENTO  316 non-null    datetime64[ns]
dtypes: datetime64[ns](3), int64(1)
memory usage: 12.4 KB

In [92]:
contratos_cargar['CONTRATOS_DESDE'] = contratos_cargar['CONTRATOS_DESDE'].dt.strftime('%Y-%m-%d')
contratos_cargar['CONTRATOS_HASTA'] = contratos_cargar['CONTRATOS_HASTA'].dt.strftime('%Y-%m-%d')
contratos_cargar['CONTRATOS_VENCIMIENTO'] = contratos_cargar['CONTRATOS_VENCIMIENTO'].dt.strftime('%Y-%m-%d')
contratos_cargar.info()

<class 'pandas.core.frame.DataFrame'>
Index: 318 entries, 0 to 327
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUPPLIER               318 non-null    int64
 1   CONTRATOS_DESDE        316 non-null    object
 2   CONTRATOS_HASTA        307 non-null    object
 3   CONTRATOS_VENCIMIENTO  316 non-null    object
dtypes: int64(1), object(3)
memory usage: 12.4+ KB

In [93]:
cursor.execute('DELETE FROM SANDBOX_PLUS.DWH.CONTRATOS_PROVEEDORES;')
succes = carga_snow_generic(df=contratos_cargar, ctx=snow, table='CONTRATOS_PROVEEDORES',
                            database='SANDBOX_PLUS', schema='DWH')

c:\Users\marcos.larran\Desktop\Github\Proyectos_Streamlit\Pricing\utils.py:104: UserWarning: Pandas Dataframe has non-standard index of type <class 'pandas.core.indexes.base.Index'> which will not be written. Consider changing the index to pd.RangeIndex(start=0,...,step=1) or call reset_index() to keep index as column(s)
  success = write_pandas(df = df, conn = ctx, table_name= table,

SUCCESS

In [4]:
prov = descargar_segmento(cursor=cursor, query='PROVEEDORES').sort_values('LISTA').reset_index(drop=True)
prov.head()

,FECHA_SOLICITUD,SUPPLIER,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,COSTO_ACTUAL,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,LISTA,ESTADO
0,2026-02-26,9066,381.0,1000003287,VENTILADOR 2 EN 1 HOMETECH USS-18721 45CM,495.72,45.0,-0.91,455.0,1,None
1,2026-02-26,9066,124.0,1000003273,AIRE ACOND. HOMETECH 12000 BTU 1.00 U,277106.26,76.0,-1.00,100.0,1,None
2,2026-02-26,9066,157.0,1000002594,PLANCHITA DE PELO HOMETECH TA-2786,155.04,12.0,-0.92,123.0,1,None
3,2026-02-26,9066,332.0,1000003299,VENTILADOR DE PIE HOMETECH US-16058A 40 CM,314.16,56.0,-0.82,5656.0,1,None
4,2026-02-26,9066,381.0,1000000003,TELEFONO DE MESA HOMETECH GCE2100,10641.86,12.0,-1.00,120.0,1,None

In [7]:
# Opciones para la columna ESTADO
opc = ["Aprobada", "Rechazada"]
dis = list(prov.columns)
dis.remove('ESTADO')
meses = {1:"ene", 2:"feb", 3:"mar", 4:"abr", 5:"may", 6:"jun",
         7:"jul", 8:"ago", 9:"sep", 10:"oct", 11:"nov", 12:"dic"}
proveedores = prov
proveedores['ESTADO'] = 'Aprobada'
proveedores.head()

,FECHA_SOLICITUD,SUPPLIER,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,COSTO_ACTUAL,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,LISTA,ESTADO
0,2026-02-26,9066,381.0,1000003287,VENTILADOR 2 EN 1 HOMETECH USS-18721 45CM,495.72,45.0,-0.91,455.0,1,Aprobada
1,2026-02-26,9066,124.0,1000003273,AIRE ACOND. HOMETECH 12000 BTU 1.00 U,277106.26,76.0,-1.00,100.0,1,Aprobada
2,2026-02-26,9066,157.0,1000002594,PLANCHITA DE PELO HOMETECH TA-2786,155.04,12.0,-0.92,123.0,1,Aprobada
3,2026-02-26,9066,332.0,1000003299,VENTILADOR DE PIE HOMETECH US-16058A 40 CM,314.16,56.0,-0.82,5656.0,1,Aprobada
4,2026-02-26,9066,381.0,1000000003,TELEFONO DE MESA HOMETECH GCE2100,10641.86,12.0,-1.00,120.0,1,Aprobada

In [8]:
it = proveedores[(proveedores['GEOG_LOCL_COD'].isna()) & (proveedores['ESTADO']=='Aprobada')]
it.head()

,FECHA_SOLICITUD,SUPPLIER,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,COSTO_ACTUAL,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,LISTA,ESTADO
9,2026-03-02,2218,NaN,1000040198,SOMBRA INDIVIDUAL VOGUE CEREZA 1.00 U,72.64,100.0,0.38,250.0,2,Aprobada
17,2026-03-05,2218,NaN,1000039208,SOMBRA INDIVIDUAL VOGUE MILITAR 1.00 U,72.64,333.0,3.58,341.0,6,Aprobada
18,2026-03-05,2218,NaN,1000042179,ESMALTE COLORAMA ROSA INCREIVE 1.00 U,39.26,191.0,3.87,192.0,6,Aprobada
19,2026-03-05,2218,NaN,1000102352,GEL CREMA HYDRAFRESH PIEL MIXTA/GR 50.00 ML,169.06,466.0,1.76,477.0,6,Aprobada
20,2026-03-05,2218,NaN,1000098662,TINTA NUTRISSE COR INTENSA RUBIO CLARO CENIZO ...,169.87,21.0,-0.88,23.0,6,Aprobada

In [9]:
loc = proveedores[(~proveedores['GEOG_LOCL_COD'].isna()) &
                  (proveedores['ESTADO']=='Aprobada')].astype({'GEOG_LOCL_COD':'int64'})
loc.head()

,FECHA_SOLICITUD,SUPPLIER,GEOG_LOCL_COD,ORIN,ARTC_ARTC_DESC,COSTO_ACTUAL,COSTO_NUEVO,INCREMENTO,PVP_SUGERIDO,LISTA,ESTADO
0,2026-02-26,9066,381,1000003287,VENTILADOR 2 EN 1 HOMETECH USS-18721 45CM,495.72,45.0,-0.91,455.0,1,Aprobada
1,2026-02-26,9066,124,1000003273,AIRE ACOND. HOMETECH 12000 BTU 1.00 U,277106.26,76.0,-1.00,100.0,1,Aprobada
2,2026-02-26,9066,157,1000002594,PLANCHITA DE PELO HOMETECH TA-2786,155.04,12.0,-0.92,123.0,1,Aprobada
3,2026-02-26,9066,332,1000003299,VENTILADOR DE PIE HOMETECH US-16058A 40 CM,314.16,56.0,-0.82,5656.0,1,Aprobada
4,2026-02-26,9066,381,1000000003,TELEFONO DE MESA HOMETECH GCE2100,10641.86,12.0,-1.00,120.0,1,Aprobada

In [14]:
camb_costo = pd.DataFrame()
for l in it['LISTA'].unique():
    df = it[it['LISTA']==l]
    for p in df['SUPPLIER'].unique():
        cc = pd.DataFrame()
        cc['Acción'] = ['Crear']
        cc['Cambio de costo'] = 324235334
        cc['Descripción de cambio de costo'] = 'Costo proovedor ' + str(p) + '. Lista ' + str(l)
        cc['Motivo'] = 5
        cc['Fecha activa'] = str(date.today().day) + '-' + meses[date.today().month] + '-' + str(date.today().year)[-2:]
        cc['Estado'] = 'Hoja de trabajo'
        cc['Origen de cambio de costo'] = 'Por artículo'
        camb_costo = pd.concat([camb_costo, cc], ignore_index=True)
camb_costo

,Acción,Cambio de costo,Descripción de cambio de costo,Motivo,Fecha activa,Estado,Origen de cambio de costo
0,Crear,324235334,Costo proovedor 2218. Lista 2,5,22-abr-26,Hoja de trabajo,Por artículo
1,Crear,324235334,Costo proovedor 2218. Lista 6,5,22-abr-26,Hoja de trabajo,Por artículo
2,Crear,324235334,Costo proovedor 2218. Lista 13,5,22-abr-26,Hoja de trabajo,Por artículo

In [22]:
cc = it[['SUPPLIER', 'LISTA']].drop_duplicates()
cc['Acción'] = 'Crear'
cc['Cambio de costo'] = 324235334
cc['Descripción de cambio de costo'] = 'Costo proovedor ' + cc['SUPPLIER'].astype('str') + '. Lista ' + cc['LISTA'].astype('str')
cc['Motivo'] = 5
cc['Fecha activa'] = str(date.today().day) + '-' + meses[date.today().month] + '-' + str(date.today().year)[-2:]
cc['Estado'] = 'Hoja de trabajo'
cc['Origen de cambio de costo'] = 'Por artículo'
camb_costo = cc[['Acción', 'Cambio de costo', 'Descripción de cambio de costo', 'Motivo',
                 'Fecha activa', 'Estado', 'Origen de cambio de costo']].reset_index(drop=True)
camb_costo

,Acción,Cambio de costo,Descripción de cambio de costo,Motivo,Fecha activa,Estado,Origen de cambio de costo
0,Crear,324235334,Costo proovedor 2218. Lista 2,5,22-abr-26,Hoja de trabajo,Por artículo
1,Crear,324235334,Costo proovedor 2218. Lista 6,5,22-abr-26,Hoja de trabajo,Por artículo
2,Crear,324235334,Costo proovedor 2218. Lista 13,5,22-abr-26,Hoja de trabajo,Por artículo

In [27]:
cc = it[['SUPPLIER', 'LISTA', 'ORIN', 'COSTO_NUEVO']].drop_duplicates()
cc['Acción'] = 'Crear'
cc['Cambio de costo'] = 324235334
cc['ID de país de origen'] = 'UY'
cc['Tipo de cambio de costo'] = 'Costo fijo'
cc['Recálculo de órdenes'] = 'Costo fijo'
cc['ID de país de entrega'] = pd.NA
camb_costo_art = cc[['Acción', 'Cambio de costo', 'SUPPLIER', 'ID de país de origen', 'ORIN',
                     'Tipo de cambio de costo', 'COSTO_NUEVO', 'Recálculo de órdenes',
                     'ID de país de entrega']].reset_index(drop=True)
camb_costo_art.columns = ['Acción', 'Cambio de costo', 'Proveedor', 'ID de país de origen', 'Artículo',
                          'Tipo de cambio de costo', 'Valor de cambio de costo', 'Recálculo de órdenes',
                          'ID de país de entrega']
camb_costo_art

,Acción,Cambio de costo,Proveedor,ID de país de origen,Artículo,Tipo de cambio de costo,Valor de cambio de costo,Recálculo de órdenes,ID de país de entrega
0,Crear,324235334,2218,UY,1000040198,Costo fijo,100.0,Costo fijo,<NA>
1,Crear,324235334,2218,UY,1000039208,Costo fijo,333.0,Costo fijo,<NA>
2,Crear,324235334,2218,UY,1000042179,Costo fijo,191.0,Costo fijo,<NA>
3,Crear,324235334,2218,UY,1000102352,Costo fijo,466.0,Costo fijo,<NA>
4,Crear,324235334,2218,UY,1000098662,Costo fijo,21.0,Costo fijo,<NA>
5,Crear,324235334,2218,UY,1000098915,Costo fijo,143.0,Costo fijo,<NA>
6,Crear,324235334,2218,UY,1000098710,Costo fijo,329.0,Costo fijo,<NA>
7,Crear,324235334,2218,UY,1000039234,Costo fijo,35.0,Costo fijo,<NA>
8,Crear,324235334,2218,UY,1000038116,Costo fijo,41.0,Costo fijo,<NA>
9,Crear,324235334,2218,UY,1000103231,Costo fijo,424.0,Costo fijo,<NA>
10,Crear,324235334,2218,UY,1000040474,Costo fijo,166.0,Costo fijo,<NA>
11,Crear,324235334,2218,UY,1000038961,Costo fijo,103.0,Costo fijo,<NA>
12,Crear,324235334,2218,UY,1000102103,Costo fijo,164.0,Costo fijo,<NA>
13,Crear,324235334,2218,UY,1000038614,Costo fijo,291.0,Costo fijo,<NA>
14,Crear,324235334,2218,UY,1000038661,Costo fijo,176.0,Costo fijo,<NA>
15,Crear,324235334,2218,UY,1000101777,Costo fijo,105.0,Costo fijo,<NA>
16,Crear,324235334,2218,UY,1000102145,Costo fijo,3.0,Costo fijo,<NA>
17,Crear,324235334,2218,UY,1000102105,Costo fijo,150.0,Costo fijo,<NA>
18,Crear,324235334,2218,UY,1000101798,Costo fijo,207.0,Costo fijo,<NA>

In [23]:
with pd.ExcelWriter("ejemplo.ods", engine="odf") as writer:
    camb_costo.to_excel(writer, sheet_name="Cambios_de_costo", index=False)
    camb_costo_art.to_excel(writer, sheet_name="Artículos_de_cambio_de_costo", index=False)

In [28]:
cc = loc[['SUPPLIER', 'LISTA', 'GEOG_LOCL_COD', 'ORIN', 'COSTO_NUEVO']].drop_duplicates()
cc['Acción'] = 'Crear'
cc['Cambio de costo'] = 324235334
cc['ID de país de origen'] = 'UY'
cc['Tipo de ubicación'] = 'Tienda'
cc['Tipo de cambio de costo'] = 'Costo fijo'
cc['Recálculo de órdenes'] = 'Costo fijo'
cc['ID de país de entrega'] = pd.NA
camb_costo_art = cc[['Acción', 'Cambio de costo', 'SUPPLIER', 'ID de país de origen', 'ORIN', 'Tipo de ubicación',
                     'GEOG_LOCL_COD', 'Tipo de cambio de costo', 'COSTO_NUEVO', 'Recálculo de órdenes',
                     'ID de país de entrega']].reset_index(drop=True)
camb_costo_art.columns = ['Acción', 'Cambio de costo', 'Proveedor', 'ID de país de origen', 'Artículo', 'Tipo de ubicación',
                          'Ubicación', 'Tipo de cambio de costo', 'Valor de cambio de costo', 'Recálculo de órdenes',
                          'ID de país de entrega']
camb_costo_art

,Acción,Cambio de costo,Proveedor,ID de país de origen,Artículo,Tipo de ubicación,Ubicación,Tipo de cambio de costo,Valor de cambio de costo,Recálculo de órdenes,ID de país de entrega
0,Crear,324235334,9066,UY,1000003287,Tienda,381,Costo fijo,45.0,Costo fijo,<NA>
1,Crear,324235334,9066,UY,1000003273,Tienda,124,Costo fijo,76.0,Costo fijo,<NA>
2,Crear,324235334,9066,UY,1000002594,Tienda,157,Costo fijo,12.0,Costo fijo,<NA>
3,Crear,324235334,9066,UY,1000003299,Tienda,332,Costo fijo,56.0,Costo fijo,<NA>
4,Crear,324235334,9066,UY,1000000003,Tienda,381,Costo fijo,12.0,Costo fijo,<NA>
5,Crear,324235334,9066,UY,1000002397,Tienda,381,Costo fijo,13.0,Costo fijo,<NA>
6,Crear,324235334,9066,UY,1000003301,Tienda,332,Costo fijo,454.0,Costo fijo,<NA>
7,Crear,324235334,9066,UY,1000002695,Tienda,405,Costo fijo,13.0,Costo fijo,<NA>
8,Crear,324235334,9066,UY,1000003274,Tienda,381,Costo fijo,34.0,Costo fijo,<NA>
9,Crear,324235334,1195,UY,1000049599,Tienda,101,Costo fijo,40.0,Costo fijo,<NA>
10,Crear,324235334,1195,UY,1000049599,Tienda,104,Costo fijo,40.0,Costo fijo,<NA>
11,Crear,324235334,1195,UY,1000049599,Tienda,120,Costo fijo,40.0,Costo fijo,<NA>
12,Crear,324235334,1195,UY,1000049599,Tienda,103,Costo fijo,40.0,Costo fijo,<NA>
13,Crear,324235334,1195,UY,1000049599,Tienda,115,Costo fijo,40.0,Costo fijo,<NA>
14,Crear,324235334,1195,UY,1000049599,Tienda,102,Costo fijo,40.0,Costo fijo,<NA>
15,Crear,324235334,1195,UY,1000049599,Tienda,108,Costo fijo,40.0,Costo fijo,<NA>
16,Crear,324235334,1195,UY,1000049579,Tienda,103,Costo fijo,87.0,Costo fijo,<NA>
17,Crear,324235334,1195,UY,1000049579,Tienda,102,Costo fijo,87.0,Costo fijo,<NA>
18,Crear,324235334,1195,UY,1000049601,Tienda,101,Costo fijo,11.0,Costo fijo,<NA>
19,Crear,324235334,1195,UY,1000049599,Tienda,101,Costo fijo,38.0,Costo fijo,<NA>
20,Crear,324235334,1195,UY,1000049598,Tienda,102,Costo fijo,9.0,Costo fijo,<NA>
21,Crear,324235334,1195,UY,1000049578,Tienda,101,Costo fijo,77.0,Costo fijo,<NA>
22,Crear,324235334,1195,UY,1000049598,Tienda,115,Costo fijo,9.0,Costo fijo,<NA>
23,Crear,324235334,1195,UY,1000049579,Tienda,101,Costo fijo,87.0,Costo fijo,<NA>
24,Crear,324235334,1195,UY,1000049579,Tienda,115,Costo fijo,87.0,Costo fijo,<NA>
25,Crear,324235334,1195,UY,1000049578,Tienda,102,Costo fijo,77.0,Costo fijo,<NA>
26,Crear,324235334,1195,UY,1000049599,Tienda,115,Costo fijo,38.0,Costo fijo,<NA>
27,Crear,324235334,1195,UY,1000049598,Tienda,101,Costo fijo,9.0,Costo fijo,<NA>
28,Crear,324235334,1195,UY,1000049578,Tienda,104,Costo fijo,77.0,Costo fijo,<NA>
29,Crear,324235334,1195,UY,1000049598,Tienda,103,Costo fijo,9.0,Costo fijo,<NA>
30,Crear,324235334,1195,UY,1000049601,Tienda,103,Costo fijo,11.0,Costo fijo,<NA>
31,Crear,324235334,1195,UY,1000049601,Tienda,104,Costo fijo,11.0,Costo fijo,<NA>
32,Crear,324235334,1195,UY,1000049579,Tienda,104,Costo fijo,87.0,Costo fijo,<NA>
33,Crear,324235334,1195,UY,1000049598,Tienda,104,Costo fijo,9.0,Costo fijo,<NA>
34,Crear,324235334,1195,UY,1000049601,Tienda,102,Costo fijo,11.0,Costo fijo,<NA>
35,Crear,324235334,1195,UY,1000049599,Tienda,102,Costo fijo,38.0,Costo fijo,<NA>
36,Crear,324235334,1195,UY,1000049578,Tienda,115,Costo fijo,77.0,Costo fijo,<NA>
37,Crear,324235334,1195,UY,1000049601,Tienda,115,Costo fijo,11.0,Costo fijo,<NA>
38,Crear,324235334,1195,UY,1000049599,Tienda,103,Costo fijo,38.0,Costo fijo,<NA>
39,Crear,324235334,1195,UY,1000049578,Tienda,103,Costo fijo,77.0,Costo fijo,<NA>
40,Crear,324235334,1195,UY,1000049599,Tienda,104,Costo fijo,38.0,Costo fijo,<NA>

In [3]:
locales = descargar_segmento(cursor, 'LOCALES')
ref = descargar_segmento(cursor, 'CANASTAS', conds=[" WHERE CANASTA = 'referente'"])
merca = descargar_segmento(cursor, 'CANASTAS', conds=[" WHERE CANASTA = 'mercado'"])
surti = descargar_segmento(cursor, 'CANASTAS', conds=[" WHERE CANASTA = 'surtido'"])

In [4]:
uploaded_file = pd.read_excel('../../cargaInicial.xlsx')
uploaded_file

,ORIN,MONTEVIDEO,CANELONES,SAN JOSE,CERRO LARGO,DURAZNO,TACUAREMBÓ,RIVERA,ARTIGAS,TREINTA Y TRES,LAVALLEJA,MALDONADO,FLORES,ROCHA,FLORIDA,SALTO,SORIANO,RIO NEGRO,COLONIA,PAYSANDU
0,1000049025,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0
1,1000049028,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0
2,1000048880,1,1,0,1,1,0,1,1,1,0,1,1,1,0,1,0,0,1,0
3,1000048984,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1
4,1000049023,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,1000037695,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
566,1000037689,1,1,1,1,1,1,0,0,1,1,1,0,0,0,0,1,0,0,0
567,1000037633,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1
568,1000037636,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1
569,1000037654,0,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,1,1

In [5]:
#Armamos archivos con referentes
referentes = uploaded_file.melt(id_vars='ORIN', value_vars=uploaded_file.columns[1:], var_name='GEOG_DPTO_DESC',
                                value_name='REFERENTE').rename(columns={'ORIN':'ITEM'})
referentes = referentes[referentes['REFERENTE']==1].drop(columns='REFERENTE')
referentes

             ITEM GEOG_DPTO_DESC
2      1000048880     MONTEVIDEO
3      1000048984     MONTEVIDEO
6      1000048971     MONTEVIDEO
7      1000048967     MONTEVIDEO
9      1000187935     MONTEVIDEO
...           ...            ...
10823  1000040363       PAYSANDU
10824  1000164208       PAYSANDU
10827  1000037633       PAYSANDU
10828  1000037636       PAYSANDU
10829  1000037654       PAYSANDU

[6413 rows x 2 columns]

In [6]:
#Agregamos columnas auxiliares en los df que corresponda para explotar
referentes['aux'] = 1
ref['aux'] = 1
locales['aux'] = 1

In [8]:
#Armamos archivo a cargar
carga = referentes.merge(locales).drop(columns=['aux', 'GEOG_DPTO_DESC'])
carga['CANASTA'] = 'referente'
carga

             ITEM  GEOG_LOCL_ID    CANASTA
0      1000048880           191  referente
1      1000048880           229  referente
2      1000048880            24  referente
3      1000048880            25  referente
4      1000048880            28  referente
...           ...           ...        ...
31213  1000037636             7  referente
31214  1000037654            18  referente
31215  1000037654            19  referente
31216  1000037654            20  referente
31217  1000037654             7  referente

[31218 rows x 3 columns]

In [9]:
#Vemos los referentes que pasan a ser mercado y los juntamos
mercado1 = ref[~ref['ITEM'].isin(referentes['ITEM'])].drop(columns='GEOG_LOCL_ID').drop_duplicates().merge(locales)[ref.columns].drop(columns='aux')
mercado2 = locales.drop(columns='GEOG_DPTO_DESC').merge(referentes.drop(columns='GEOG_DPTO_DESC').drop_duplicates()).drop(columns='aux').merge(carga, how='left', indicator=True)
mercado = pd.concat([mercado1, mercado2[mercado2['_merge']!='both'].drop(columns='_merge')],
                    ignore_index=True)
mercado['CANASTA'] = 'mercado'
mercado

       GEOG_LOCL_ID        ITEM  CANASTA
0                 2  1000049120  mercado
1                 3  1000049120  mercado
2                 4  1000049120  mercado
3                 5  1000049120  mercado
4               191  1000049120  mercado
...             ...         ...      ...
40405           322  1000099231  mercado
40406           322  1000099234  mercado
40407           322  1000057461  mercado
40408           322  1000048124  mercado
40409           322  1000048121  mercado

[40410 rows x 3 columns]

In [15]:
merca[(~merca['ITEM'].isin(carga['ITEM'].unique())) & (~merca['ITEM'].isin(mercado['ITEM'].unique()))]

        GEOG_LOCL_ID        ITEM  CANASTA
188                2  1000162728  mercado
189               24  1000162728  mercado
190               32  1000162728  mercado
191               49  1000162728  mercado
192               61  1000162728  mercado
...              ...         ...      ...
327021            91  1000053222  mercado
327022            73  1000053222  mercado
327023           134  1000053222  mercado
327024            13  1000053222  mercado
327025           302  1000053222  mercado

[299202 rows x 3 columns]

In [16]:
carga_mercado = pd.concat([merca[(~merca['ITEM'].isin(carga['ITEM'].unique())) & (~merca['ITEM'].isin(mercado['ITEM'].unique()))],
                               mercado], ignore_index=True)
carga_mercado

        GEOG_LOCL_ID        ITEM  CANASTA
0                  2  1000162728  mercado
1                 24  1000162728  mercado
2                 32  1000162728  mercado
3                 49  1000162728  mercado
4                 61  1000162728  mercado
...              ...         ...      ...
339607           322  1000099231  mercado
339608           322  1000099234  mercado
339609           322  1000057461  mercado
339610           322  1000048124  mercado
339611           322  1000048121  mercado

[339612 rows x 3 columns]

In [23]:
mp = descargar_segmento(cursor, 'CANASTAS', conds=[" WHERE CANASTA = 'marca propia'"])
mp

       GEOG_LOCL_ID        ITEM       CANASTA
0                 2  1000050185  marca propia
1                24  1000050185  marca propia
2                32  1000050185  marca propia
3                49  1000050185  marca propia
4                61  1000050185  marca propia
...             ...         ...           ...
59873            91  1000348112  marca propia
59874            73  1000348112  marca propia
59875           134  1000348112  marca propia
59876            13  1000348112  marca propia
59877           302  1000348112  marca propia

[59878 rows x 3 columns]

In [22]:
exclu = descargar_segmento(cursor, 'CANASTAS', conds=[" WHERE CANASTA = 'excluido'"])
exclu

        GEOG_LOCL_ID        ITEM   CANASTA
0                  2  1000406859  excluido
1                 24  1000406859  excluido
2                 32  1000406859  excluido
3                 49  1000406859  excluido
4                 61  1000406859  excluido
...              ...         ...       ...
284627            91  1000300284  excluido
284628            73  1000300284  excluido
284629           134  1000300284  excluido
284630            13  1000300284  excluido
284631           302  1000300284  excluido

[284632 rows x 3 columns]

In [21]:
carga_surtido = surti[(~surti['ITEM'].isin(carga_mercado['ITEM'].unique())) &
                      (~surti['ITEM'].isin(carga['ITEM'].unique()))]
carga_surtido

         GEOG_LOCL_ID        ITEM  CANASTA
0                   2  1000048276  surtido
1                  24  1000048276  surtido
2                  32  1000048276  surtido
3                  49  1000048276  surtido
4                  61  1000048276  surtido
...               ...         ...      ...
3343011            91  1000051862  surtido
3343012            73  1000051862  surtido
3343013           134  1000051862  surtido
3343014            13  1000051862  surtido
3343015           302  1000051862  surtido

[3342640 rows x 3 columns]

In [73]:
mercado1['ITEM'].value_counts()

ITEM
1000049120    94
1000049195    94
1000041930    94
1000041824    94
1000041943    94
              ..
1000460709    94
1000055868    94
1000054577    94
1000050419    94
1000056479    94
Name: count, Length: 192, dtype: int64

In [77]:
carga = referentes.merge(locales).drop(columns=['aux', 'GEOG_DPTO_DESC'])
carga['CANASTA'] = 'referente'
carga

             ITEM  GEOG_LOCL_ID    CANASTA
0      1000048880           191  referente
1      1000048880           229  referente
2      1000048880            24  referente
3      1000048880            25  referente
4      1000048880            28  referente
...           ...           ...        ...
31213  1000037636             7  referente
31214  1000037654            18  referente
31215  1000037654            19  referente
31216  1000037654            20  referente
31217  1000037654             7  referente

[31218 rows x 3 columns]

In [75]:
carga['ITEM'].value_counts()

ITEM
1000050434    86
1000523176    86
1000570013    86
1000050762    86
1000050800    86
              ..
1000048564     1
1000052028     1
1000461487     1
1000051908     1
1000048566     1
Name: count, Length: 570, dtype: int64

In [55]:
referentes

             ITEM GEOG_DPTO_DESC  aux
2      1000048880     MONTEVIDEO    1
3      1000048984     MONTEVIDEO    1
6      1000048971     MONTEVIDEO    1
7      1000048967     MONTEVIDEO    1
9      1000187935     MONTEVIDEO    1
...           ...            ...  ...
10823  1000040363       PAYSANDU    1
10824  1000164208       PAYSANDU    1
10827  1000037633       PAYSANDU    1
10828  1000037636       PAYSANDU    1
10829  1000037654       PAYSANDU    1

[6413 rows x 3 columns]

In [56]:
referentes['ITEM'].unique().size

570

In [57]:
carga

             ITEM  GEOG_LOCL_ID
0      1000048880           191
1      1000048880           229
2      1000048880            24
3      1000048880            25
4      1000048880            28
...           ...           ...
31213  1000037636             7
31214  1000037654            18
31215  1000037654            19
31216  1000037654            20
31217  1000037654             7

[31218 rows x 2 columns]

In [58]:
locales.drop(columns='GEOG_DPTO_DESC').merge(referentes.drop(columns='GEOG_DPTO_DESC').drop_duplicates()).drop(columns='aux')

       GEOG_LOCL_ID        ITEM
0                 2  1000048880
1                 2  1000048984
2                 2  1000048971
3                 2  1000048967
4                 2  1000187935
...             ...         ...
53575           322  1000099231
53576           322  1000099234
53577           322  1000057461
53578           322  1000048124
53579           322  1000048121

[53580 rows x 2 columns]

In [40]:
carga

             ORIN  GEOG_LOCL_ID
0      1000048880           191
1      1000048880           229
2      1000048880            24
3      1000048880            25
4      1000048880            28
...           ...           ...
31213  1000037636             7
31214  1000037654            18
31215  1000037654            19
31216  1000037654            20
31217  1000037654             7

[31218 rows x 2 columns]

In [79]:
mercado2 = locales.drop(columns='GEOG_DPTO_DESC').merge(referentes.drop(columns='GEOG_DPTO_DESC').drop_duplicates()).drop(columns='aux').merge(carga, how='left', indicator=True)
mercado = pd.concat([mercado1, mercado2[mercado2['_merge']!='both'].drop(columns='_merge')], ignore_index=True)
mercado['CANASTA'] = 'mercado'
mercado

       GEOG_LOCL_ID        ITEM  CANASTA
0                 2  1000049120  mercado
1                 3  1000049120  mercado
2                 4  1000049120  mercado
3                 5  1000049120  mercado
4               191  1000049120  mercado
...             ...         ...      ...
40405           322  1000099231  mercado
40406           322  1000099234  mercado
40407           322  1000057461  mercado
40408           322  1000048124  mercado
40409           322  1000048121  mercado

[40410 rows x 3 columns]

In [61]:
merca = descargar_segmento(cursor, 'CANASTAS', conds=["'mercado'"])
merca

        GEOG_LOCL_ID        ITEM  CANASTA
0                  2  1000049023  mercado
1                 24  1000049023  mercado
2                 32  1000049023  mercado
3                 49  1000049023  mercado
4                 61  1000049023  mercado
...              ...         ...      ...
327021            91  1000053222  mercado
327022            73  1000053222  mercado
327023           134  1000053222  mercado
327024            13  1000053222  mercado
327025           302  1000053222  mercado

[327026 rows x 3 columns]

In [67]:
merca[~merca['ITEM'].isin(mercado['ITEM'].unique())]#['ITEM'].value_counts()

        GEOG_LOCL_ID        ITEM  CANASTA
188                2  1000162728  mercado
189               24  1000162728  mercado
190               32  1000162728  mercado
191               49  1000162728  mercado
192               61  1000162728  mercado
...              ...         ...      ...
327021            91  1000053222  mercado
327022            73  1000053222  mercado
327023           134  1000053222  mercado
327024            13  1000053222  mercado
327025           302  1000053222  mercado

[299202 rows x 3 columns]

In [80]:
print(f'asdasd {len(carga)} sadasd')

asdasd 31218 sadasd

In [68]:
carga_mercado = pd.concat([mercado, merca[~merca['ITEM'].isin(mercado['ITEM'].unique())]], ignore_index=True)
carga_mercado

        GEOG_LOCL_ID        ITEM  CANASTA
0                  2  1000049120  mercado
1                  3  1000049120  mercado
2                  4  1000049120  mercado
3                  5  1000049120  mercado
4                191  1000049120  mercado
...              ...         ...      ...
339607            91  1000053222  mercado
339608            73  1000053222  mercado
339609           134  1000053222  mercado
339610            13  1000053222  mercado
339611           302  1000053222  mercado

[339612 rows x 3 columns]

In [22]:
locales = pd.read_csv('C:/Users/marcos.larran/Downloads/LOCALES.csv')
locales

     GEOG_LOCL_ID  CODIGO_TIENDA
0               8            132
1               9            134
2              11            140
3              12            143
4              13            144
..            ...            ...
240           333            450
241           334            451
242           335            452
243           336            454
244           337            453

[245 rows x 2 columns]

In [2]:
nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/Nielsen viejo.csv')
nielsen

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,PRIORIDAD,GEOG_LOCL_ID
0,100356243,DEVOTO EXPRESS SUC. 3113 SARANDI 690 A JUNCAL ...,S R NDI 690- JUNC L 1347 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,6,21
1,100356250,DEVOTO EXPRESS SUC. 3121 CANELONES 1251 ESQ. C...,C NELONES 1251 ESQ C QUIJ NO NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,7,21
2,100356180,DISCO SUC. 117 MALDONADO 1024 SUR GRANMONTEVIDEO,M LDON DO-1024-SUR NN,GRAN MONTEVIDEO B,MONTEVIDEO,BARRIO SUR,DISCO,DISCO,101,9,21
3,100356170,DISCO SUC. 103 ARENAL GDE. 1376 CORDON GRANMON...,REN L GDE-1376-CORDON NN,GRAN MONTEVIDEO B,MONTEVIDEO,CORDON,DISCO,DISCO,101,10,21
4,100356367,DEVOTO EXPRESS SUC. 3132 SAN JOSE 1085 / 1087 0,S N JOSE 1085 / 1087 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,101,8,21
...,...,...,...,...,...,...,...,...,...,...,...
430,100356186,DISCO SUC. 125 MCAL. SOLANO LOPEZ 1680 0,NN NN,GRAN MONTEVIDEO A,MONTEVIDEO,BUCEO,DISCO,DISCO,420,3,322
431,100356252,DEVOTO EXPRESS SUC. 3124 CNO. CARRASCO 6955 SE...,CNO C RR SCO 6955 NN,GRAN MONTEVIDEO A,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,420,2,322
432,100356159,TIENDA INGLESA SUC. 1 AV. ITALIA ESQ. BOLIVIA ...,V IT LI--ESQ BOLIVI- 5820-M LVIN NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,4,322
433,100356160,TIENDA INGLESA SUC. 2 SCHROEDER 6436 CARRASCO ...,SCHROEDER- 6436-C RR SCO NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,5,322
434,100356201,DEVOTO SUC. 3003 AV. GRAL RIVERA 4502 BRISAS G...,V GR L RIVER- 4502-BRIS S NN,GRAN MONTEVIDEO A,MONTEVIDEO,MALVIN,DEVOTO,DEVOTO,420,1,322

In [23]:
c_nielsen = pd.read_excel('C:/Users/marcos.larran/Downloads/correcciones Nielsen.xlsx')
print(c_nielsen.shape)
c_nielsen

(21, 2)

    CODIGO_TIENDA   STORE_ID
0             143  108282396
1             111  108282396
2             156  108282396
3             316  108282396
4             145  100356446
5             335  100356446
6             139  100356353
7             139  106558845
8             155  100356353
9             155  106558845
10            126  100356353
11            126  106558845
12            331  100356353
13            331  106558845
14            332  100356353
15            332  106558845
16            333  100356353
17            333  106558845
18            417  100356206
19            417  100356211
20            417  100356246

In [16]:
info_nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/PriceMaster_UY_grupo_tata.csv',
                           encoding='ISO-8859-1', sep='|')
info_nielsen = info_nielsen[['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA',
                             'CITY', 'RETAILER', 'BANNER']].drop_duplicates()
info_nielsen

C:\Users\marcos.larran\AppData\Local\Temp\ipykernel_22396\395866159.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  info_nielsen = pd.read_csv('C:/Users/marcos.larran/Downloads/PriceMaster_UY_grupo_tata.csv',

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER
0,100356162,TIENDA INGLESA SUC. 4 J.B. BLANCO 966 POCITOS ...,JB BL NCO- 966-POCITOS NN,GRAN MONTEVIDEO A,MONTEVIDEO,POCITOS,TIENDA INGLESA,TIENDA INGLESA
163,100356169,DISCO SUC. 102 AV. AGRACIADA 2986 PRADO GRANMO...,V-GR CI D- 2986-PR DO NN,GRAN MONTEVIDEO B,MONTEVIDEO,CAPURRO,DISCO,DISCO
708,100356175,DISCO SUC. 111 8 DE OCTUBRE 2681 TRES CRUCES G...,8 DE OCTUBRE- 2681-TRES CRUCES NN,GRAN MONTEVIDEO B,MONTEVIDEO,PQE BATTLE,DISCO,DISCO
798,100356176,DISCO SUC. 112 8 DE OCTUBRE 4786 UNION GRANMON...,8 DE OCTUBRE-4786-UNION NN,GRAN MONTEVIDEO B,MONTEVIDEO,MARONAS,DISCO,DISCO
1230,100356177,DISCO SUC. 113 CHUCARRO 1320 POCITOS GRANMONTE...,CHUC RRO-1320-POCITOS NN,GRAN MONTEVIDEO A,MONTEVIDEO,POCITOS,DISCO,DISCO
...,...,...,...,...,...,...,...,...
1441042,245853700,EL DORADOSUC 2510DR MORQUIO 600 ESQUINA EUSEBI...,DR MORQUIO 600 ESQUINA EUSEBIO PIREZ NN,INTERIOR CENTRO,DURAZNO,NaN,EL DORADO,EL DORADO
1445679,245853701,EL DORADOSUC 57019 DE ABRIL Y GRAL ARTIGASAMAL...,19 DE ABRIL Y GRAL ARTIGASA NN,INTERIOR ESTE,MALDONADO,NaN,EL DORADO,EL DORADO
1461395,287358763,EL DORADOSUC 2320ÿESPINILLO Y CORONILLAÿFRAY B...,ÿESPINILLO Y CORONILLAÿ NN,INTERIOR LITORAL,RIO NEGRO,NaN,EL DORADO,EL DORADO
1461452,288159883,TATASUC 420GENERAL FLORES 2928MONTEVIDEO,GENERAL FLORES 2928 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,TATA,TATA
1461593,305903691,TIENDA INGLESASUC 450AV FRANCISCA FAJARDO Y RA...,AV FRANCISCA FAJARDO Y RAFAEL BARRADAS NN,PUNTA DEL ESTE,MALDONADO,NaN,TIENDA INGLESA,TIENDA INGLESA

In [20]:
info_nielsen['STORE_ID'].value_counts()

STORE_ID
100356162    1
100356449    1
100356445    1
100356444    1
100356443    1
            ..
100356145    1
100356141    1
100356206    1
100356205    1
305903691    1
Name: count, Length: 328, dtype: int64

In [24]:
nielsen_nuevo = c_nielsen.merge(info_nielsen).merge(locales)
print(nielsen_nuevo.shape)
nielsen_nuevo.head()

(21, 10)

,CODIGO_TIENDA,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,GEOG_LOCL_ID
0,143,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,12
1,111,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,2
2,156,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,47
3,316,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,83
4,145,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,14

In [25]:
nielsen.columns

Index(['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
       'RETAILER', 'BANNER', 'LOCL_COD', 'PRIORIDAD', 'GEOG_LOCL_ID'],
      dtype='object')

In [27]:
nielsen_nuevo = nielsen_nuevo[['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
                               'RETAILER', 'BANNER', 'CODIGO_TIENDA', 'GEOG_LOCL_ID']]
nielsen_nuevo.columns = ['STORE_ID', 'STORE', 'STORE_ADDRESS', 'AREA', 'SUB_AREA', 'CITY',
                         'RETAILER', 'BANNER', 'LOCL_COD', 'GEOG_LOCL_ID']
nielsen_nuevo

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,GEOG_LOCL_ID
0,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,143,12
1,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,111,2
2,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,156,47
3,108282396,EL DORADO SUC. 1710 BLVR. ARTIGAS Y AVENIDA SALTO,BLVR. ARTIGAS Y AVENIDA SALTO NN,INTERIOR LITORAL,PAYSANDU,NaN,EL DORADO,EL DORADO,316,83
4,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,145,14
5,100356446,EL DORADO SUC. 1220 LIBERTAD 1034 SARANDI GRANDE,LIBERT D 1034 NN,INTERIOR CENTRO,FLORIDA,CENTRO,EL DORADO,EL DORADO,335,102
6,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,139,10
7,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,139,10
8,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,155,45
9,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,155,45
10,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,126,5
11,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,126,5
12,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,331,98
13,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,331,98
14,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,332,99
15,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,332,99
16,100356353,EL DORADO SUC. 1250 CARLOS BERRUTI ESQ FLORENC...,C RLOS BERRUTI ESQUIN-FLORENCIO S NCHES NN,INTERIOR NORDESTE,TACUAREMBO,NaN,EL DORADO,EL DORADO,333,100
17,106558845,EL DORADOSUC. 1260AV ANGELA B LOPEZ Y FLORENCI...,AVENIDA ANGELA B DE LOPEZ ESQUINA FLORENCIO SA...,INTERIOR NORDESTE,TACUAREMBO,CORDON,EL DORADO,EL DORADO,333,100
18,100356206,DEVOTO SUC. 3008 AV. GRAL. SAN MARTIN 3709 SAN...,V GR L S N M RTIN-3709-S N M RTIN NN,GRAN MONTEVIDEO B,MONTEVIDEO,CERRITO,DEVOTO,DEVOTO,417,66
19,100356211,DEVOTO SUC. 3016 SAN MARTIN * FOMENTO SAN MART...,S N M RTIN-FOMENTO--S N M RTIN NN,GRAN MONTEVIDEO B,MONTEVIDEO,PRADO,DEVOTO,DEVOTO,417,66
20,100356246,DEVOTO EXPRESS SUC. 3122 L. A. HERRERA 2940 SE...,L- HERRER-2940 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,417,66

In [28]:
nielsen_final = pd.concat([nielsen, nielsen_nuevo], ignore_index=True).sort_values(by=['LOCL_COD',
                                                                                       'PRIORIDAD'])
nielsen_final

,STORE_ID,STORE,STORE_ADDRESS,AREA,SUB_AREA,CITY,RETAILER,BANNER,LOCL_COD,PRIORIDAD,GEOG_LOCL_ID
7,141175690,EL DORADO SUC 2021?18 DE JULIO 2006 ESQUINA PA...,18 DE JULIO 2006 ESQUINA-PABLO DE MARIA NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,1.0,21
8,145749110,EL DORADO SUC 2022 PEATONAL SARANDI 584 MONTEV...,PEATONAL SARANDI 584 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,2.0,21
9,149665397,EL DORADO SUC 2023 18 DE JULIO 1807 MONTEVIDEO,18 DE JULIO 1807 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,3.0,21
10,164712852,EL DORADO SUC 2050 GARIBALDI 2579 MONTEVIDEO,GARIBALDI 2579 NN,GRAN MONTEVIDEO B,MONTEVIDEO,NaN,EL DORADO,EL DORADO,101,4.0,21
5,100573892,RED EXPRESS SUC 145 AVDA URUGUAY 1104 SECCION 106,AVDA URUGUAY 1104 NN,GRAN MONTEVIDEO B,MONTEVIDEO,MONTEVIDEO,TIENDA INGLESA,AUTOSERVICIOS TIENDA INGLESA,101,5.0,21
...,...,...,...,...,...,...,...,...,...,...,...
434,100356201,DEVOTO SUC. 3003 AV. GRAL RIVERA 4502 BRISAS G...,V GR L RIVER- 4502-BRIS S NN,GRAN MONTEVIDEO A,MONTEVIDEO,MALVIN,DEVOTO,DEVOTO,420,1.0,322
431,100356252,DEVOTO EXPRESS SUC. 3124 CNO. CARRASCO 6955 SE...,CNO C RR SCO 6955 NN,GRAN MONTEVIDEO A,MONTEVIDEO,NaN,DEVOTO,DEVOTO EXPRESS,420,2.0,322
430,100356186,DISCO SUC. 125 MCAL. SOLANO LOPEZ 1680 0,NN NN,GRAN MONTEVIDEO A,MONTEVIDEO,BUCEO,DISCO,DISCO,420,3.0,322
432,100356159,TIENDA INGLESA SUC. 1 AV. ITALIA ESQ. BOLIVIA ...,V IT LI--ESQ BOLIVI- 5820-M LVIN NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,4.0,322
433,100356160,TIENDA INGLESA SUC. 2 SCHROEDER 6436 CARRASCO ...,SCHROEDER- 6436-C RR SCO NN,GRAN MONTEVIDEO A,CARRASCO,CARRASCO,TIENDA INGLESA,TIENDA INGLESA,420,5.0,322

In [30]:
nielsen_final.to_excel('NIELSEN COMPLETO.xlsx', index=False)

In [10]:
f = datetime.now().replace(day=22, hour=19, minute=25, second=41).strftime('%Y%m%d_%H%M%S')

In [3]:
user, cursor, snow = snowflake_login()

Intento 1
Error: 251005: User is empty
Incorrect Password - provide again
Intento 2
Correct Password - connected to SNOWFLAKE

In [12]:
duplicados = descargar_segmento(cursor, 'DUPLICADOS', cond="'" + f + "'")
duplicados

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [11]:
checks = descargar_segmento(cursor, query='TOTAL', cond="'" + f + "'")
checks

,ORIN,GEOG_LOCL_COD,PVP_NUEVO,EFFECTIVE_DATE,FAMILIA,INTEGRANTES_FAMILIA,CANASTA,ARTC_ARTC_DESC,ESTADO,ESTA_EN_PROMO,EXCLUIDO_COMERCIAL,PRECIO_DIFERENTE
0,1000505780,146,105,None,1000505777,3,surtido,GRISINES CRI CROC INTEGRALES EL TRIGAL 145 G,4,0,0,0
1,1000505779,168,105,None,1000505777,3,surtido,GRISINES CRI CROC CLASICOS EL TRIGAL 145 GR,4,0,0,0
2,1000504782,104,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
3,1000057500,149,690,None,1000057500,1,surtido,QUESO SBRINZ PREMIUM FARMING COPETIN 1.00 KG,4,0,0,0
4,1000504782,329,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
519,1000504782,168,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
520,1000505777,145,105,None,1000505777,3,surtido,GRISINES EL TRIGAL CRI CROC SIN SAL 145 GR,4,0,0,0
521,1000157000,146,440,None,1000157000,1,referente,JAMON COCIDO DELIZIA SARUBBI.,4,0,0,0
522,1000504782,173,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1
523,1000504782,314,114,None,1000504782,1,surtido,GALLETA COFLER BA?ADAS CHOCOLATE 132.8 GR,4,1,0,1

In [14]:
final = descargar_segmento(cursor, query='FINAL', cond="'" + f + "'")
final

           ORIN CODIGO_TIENDA  PVP_NUEVO
0    1000057447           151        680
1    1000057447           157        740
2    1000057301           159        450
3    1000353250           153        310
4    1000505780           159        105
..          ...           ...        ...
390  1000057084           317        590
391  1000505780           318        105
392  1000505779           322        105
393  1000057156           323        550
394  1000505777           324        105

[395 rows x 3 columns]

In [15]:
datos = descargar_segmento(cursor, 'DATOS', cond="'" + f + "'")
datos

,ZONE_NODE_TYPE,ZONE_GROUP_ID,ZONE_ID,LOCATION,ITEM,DIFF_ID,SKULIST,LINK_CODE,CHANGE_TYPE,CHANGE_AMOUNT,...,PRICE_GUIDE_ID,EFFECTIVE_DATE,REASON_CODE,VENDOR_FUNDED_IND,FUNDING_TYPE,FUNDING_AMOUNT,FUNDING_AMOUNT_CURRENCY,FUNDING_PERCENT,DEAL_ID,DEAL_DETAIL_ID
0,0,None,None,151,1000057447,None,None,None,2,680,...,None,2025-07-23,2,0,None,None,None,None,None,None
1,0,None,None,157,1000057447,None,None,None,2,740,...,None,2025-07-23,2,0,None,None,None,None,None,None
2,0,None,None,159,1000057301,None,None,None,2,450,...,None,2025-07-23,2,0,None,None,None,None,None,None
3,0,None,None,153,1000353250,None,None,None,2,310,...,None,2025-07-23,2,0,None,None,None,None,None,None
4,0,None,None,159,1000505780,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,0,None,None,317,1000057084,None,None,None,2,590,...,None,2025-07-23,2,0,None,None,None,None,None,None
391,0,None,None,318,1000505780,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
392,0,None,None,322,1000505779,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None
393,0,None,None,323,1000057156,None,None,None,2,550,...,None,2025-07-23,2,0,None,None,None,None,None,None
394,0,None,None,324,1000505777,None,None,None,2,105,...,None,2025-07-23,2,0,None,None,None,None,None,None

In [7]:
with open('Queries/DUPLICADOS.sql', 'r', encoding="utf8") as file: command = file.read()
command

'WITH PP AS (\nSELECT\n    DISTINCT A.CODIGO_TIENDA, B.FAMILIA, COUNT(DISTINCT A.PVP_NUEVO) AS P\nFROM\n    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A\nLEFT JOIN\n    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B\nON\n    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD\nWHERE\n    FECHA_EJECUCION = (SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)\nAND\n    TABLA={f}\nGROUP BY ALL\n)\n\nSELECT\n    A.*, B.FAMILIA, B.ARTC_ARTC_DESC, B.STCK_PRECIO_VENTA_DIA_CIVA\nFROM\n    SANDBOX_PLUS.DWH.INPUT_PRICING_ACUMULADO A\nJOIN\n    SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS B\nON\n    A.ORIN = B.ORIN AND A.CODIGO_TIENDA = B.GEOG_LOCL_COD\nJOIN\n    PP\nON\n    A.CODIGO_TIENDA = PP.CODIGO_TIENDA AND B.FAMILIA = PP.FAMILIA AND P>1\nWHERE\n    FECHA_EJECUCION=(SELECT MAX(FECHA_EJECUCION) FROM SANDBOX_PLUS.DWH.RESULTADO_PRICING_HISTORICO_BIS)\nAND\n    TABLA={f}\nORDER BY\n    GEOG_LOCL_COD, B.FAMILIA;'

In [8]:
cursor.execute(command.format(f=f))

In [ ]:
d = cursor.fetch_pandas_all()
d

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [5]:
c = "WHERE LGL.GEOG_LOCL_COD IN (101, 115) AND LAA.ORIN IN ('1000038127')"

In [12]:
with open('Queries/PRECIOS.sql', 'r', encoding="utf8") as file: command = file.read()
command

"WITH P AS (\nSELECT\n    ARTC_ARTC_ID, GEOG_LOCL_ID, MEDIAN(STCK_PRECIO_VENTA_DIA_CIVA) AS PRECIO_MEDIANO\nFROM\n    MSTRDB.DWH.FT_STOCK\nWHERE\n    TIEM_DIA_ID = CURRENT_DATE - 30\nGROUP BY ALL\n)\n\n, STOCK AS (\nSELECT\n    DISTINCT FS.ARTC_ARTC_ID, FS.GEOG_LOCL_ID, FS.STCK_PRECIO_VENTA_DIA_CIVA AS PVP_ACTUAL,\n    CASE\n        WHEN FCUR.ORIGIN_COUNTRY_ID = 'UYU' THEN FCUR.COSTO_UNITARIO_RMS\n        ELSE FS.STCK_COSTO_PROM_POND\n    END AS COSTO_UNITARIO,\n    COSTO_UNITARIO * ROUND(FS.STCK_PRECIO_VENTA_DIA_CIVA/FS.STCK_PRECIO_VENTA_DIA, 2) AS COSTO_UNITARIO_CON_IVA\nFROM\n    MSTRDB.DWH.FT_STOCK FS\nJOIN\n    MSTRDB.DWH.FT_COSTO_UNITARIO_RMS FCUR\nON\n    FS.GEOG_LOCL_ID = FCUR.GEOG_LOCL_ID AND FS.ARTC_ARTC_ID = FCUR.ARTC_ARTC_ID\n    AND FCUR.TIEM_DIA_ID = (SELECT MAX(TIEM_DIA_ID) FROM MSTRDB.DWH.FT_COSTO_UNITARIO_RMS)\nWHERE\n    FS.TIEM_DIA_ID = CURRENT_DATE - 1\n)\n\nSELECT\n    LAA.ORIN, LGL.GEOG_LOCL_COD AS LOCAL, PVP_ACTUAL, PRECIO_MEDIANO, COSTO_UNITARIO_CON_IVA,\n    ROUND(DIV0(PVP_ACTUAL - COSTO_UNITARIO_CON_IVA, PVP_ACTUAL), 2) AS MARGEN\nFROM\n    STOCK AS FS\nJOIN\n    MSTRDB.DWH.LU_ARTC_ARTICULO LAA\nON\n    FS.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID\nJOIN\n    MSTRDB.DWH.LU_GEOG_LOCAL LGL\nON\n    FS.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID\nJOIN\n    P\nON\n    FS.ARTC_ARTC_ID = P.ARTC_ARTC_ID AND FS.GEOG_LOCL_ID = P.GEOG_LOCL_ID\n{cond};"

In [15]:
cursor.execute(command.format(cond=c))

In [16]:
p = cursor.fetch_pandas_all()
p

,ORIN,LOCAL,PVP_ACTUAL,PRECIO_MEDIANO,COSTO_UNITARIO_CON_IVA,MARGEN
0,1000038127,101,245.0,244.0,156.404,0.36
1,1000038127,115,198.0,244.0,156.404,0.21

In [4]:
duplicados = descargar_segmento(cursor, 'DUPLICADOS', cond=f)
duplicados

Empty DataFrame
Columns: [CODIGO_TIENDA, ORIN, PVP_NUEVO, EFFECTIVE_DATE, TABLA, FAMILIA, ARTC_ARTC_DESC, STCK_PRECIO_VENTA_DIA_CIVA]
Index: []

In [7]:
p = descargar_segmento(cursor, 'PRECIOS', cond=c)
p

,ORIN,LOCAL,PVP_ACTUAL,PRECIO_MEDIANO,COSTO_UNITARIO_CON_IVA,MARGEN
0,1000038127,101,245.0,244.0,156.404,0.36
1,1000038127,115,198.0,244.0,156.404,0.21

In [ ]:
filtros_posibles = {'PROMOCION':'ESTA_EN_PROMO = 0',
                    'EXCLUIDOS COMERCIAL':'EXCLUIDO_COMERCIAL = 0',
                        'ACTIVOS':'ARTC_ESTA_ID = 4',
                        'PRECIO DIFERENTE':'S.STCK_PRECIO_VENTA_DIA_CIVA <> A.PVP_NUEVO'}
filtros = []
todos_los_filtros = []
for f in filtros:
    todos_los_filtros.append(filtros_posibles[f])
if len(todos_los_filtros) > 0:
    todos_los_filtros = ' AND ' + ' AND '.join(todos_los_filtros)
else:
    todos_los_filtros = ''
todos_los_filtros

''

In [18]:
' AND '.join(todos_los_filtros)

''

In [20]:
if len(todos_los_filtros) > 0:
    todos_los_filtros = ' AND ' + ' AND '.join(todos_los_filtros)